package xeadEditor;

/*
 * Copyright (c) 2011 WATANABE kozo <qyf05466@nifty.com>,
 * All rights reserved.
 *
 * This file is part of XEAD Editor.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the XEAD Project nor the names of its contributors
 *       may be used to endorse or promote products derived from this software
 *       without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

public class Res extends java.util.ListResourceBundle {
	private static final Object[][] contents = new String[][]{
		{ "About", "About XEAD" },
		{ "AcceptMinus", "Accept Minus" },
		{ "Action", "Action" },
		{ "ActionAddBlankRow", "Add a blank row" },
		{ "ActionAddRows", "Add rows" },
		{ "ActionAddRowWithSelected", "Add rows with selected" },
		{ "ActionAfterInsert", "After Insert" },
		{ "ActionBackToSelectList", "Back to Select-List" },
		{ "ActionCall", " is to be called" },
		{ "ActionCallDTLFunctionToAdd", "Call DTL function to add" },
		{ "ActionCallFunction", "Call function" },
		{ "ActionCallHDRFunction", "Call HDR function" },
		{ "ActionDelete", "Delete" },
		{ "ActionExit", "Exit" },
		{ "ActionGoToCopyMode", "Go to Copy-Mode" },
		{ "ActionGoToEditMode", "Go to Edit-Mode and update" },
		{ "ActionGoToUpdateList", "Go to Update-List" },
		{ "ActionOutputEXCEL", "Output into EXCEL" },
		{ "ActionRemoveRow", "Remove the row" },
		{ "ActionReturnNull", "Return Null Key" },
		{ "ActionUpdate", "Update with editted values" },
		{ "ActiveWhere", "Active Where" },
		{ "Add", "Add" },
		{ "AddChild", "Add child-node" },
		{ "AddFields", "Select Fields to be Added" },
		{ "AddFunction", "Add a Function" },
		{ "AddIndex", "Add Index" },
		{ "AddIndexMessage", "Specify physical fields with ';' to separate them.\nBy putting '(D)' after fieldID"," it will work as DESCENT order field." },
		{ "AddJoinTable", "Add Join Table" },
		{ "AddJoinTableMessage1", "Specify ID and alias(if neccessary) of table to be joined." },
		{ "AddJoinTableMessage2", "Specify field IDs of " },
		{ "AddJoinTableMessage3", " to Join-To keys, and corresponding data source names of " },
		{ "AddJoinTableMessage4", " to Join-With keys. You can use ';' to separate IDs." },
		{ "AddKeyMessage", "Specify physical fields with ';' to separate them." },
		{ "AddMode", "Add Mode" },
		{ "AddNewFields", "Add New Fields" },
		{ "AddNewMenus", "Add New Menus" },
		{ "AddNewSubsystems", "Add New Subsystems" },
		{ "AddNewTables", "Add New Tables" },
		{ "AddPKey", "Add Primary Key" },
		{ "AddRow", "Add Row" },
		{ "AddRowDetailRowNo", "Auto Detail No" },
		{ "AddRowList", "List To Add Rows" },
		{ "AddRowListColumn", "Column on Add Row List" },
		{ "AddRowListFieldsDialogComment", "* Specify fields(with alias) returned from Add-Row-List with ';' to separate them." },
		{ "AddRowListFieldsDialogTitle", "Add-Row-List Return Fields" },
		{ "AddRowListOrderBy", "Order-By Field of Add Row List" },
		{ "AddRowListReturnFromField", "Return-From Field from Add Row List" },
		{ "AddRowListReturnFromFieldShort", "Return-From Field" },
		{ "AddRowListReturnToField", "Return-To Field from Add Row List" },
		{ "AddRowListReturnToFieldShort", "Return-To Field" },
		{ "AddRowListTable", "Table for Add Row List" },
		{ "AddRowListTableDialogComment", "* Add-Row-List table is used to list selectable keys for a new row to be added." },
		{ "AddRowListTableDialogTitle", "Add-Row-List Table and Key" },
		{ "AddRowListWithField", "With-Key Fields of List Table" },
		{ "AddRowListWithFieldShort", "With-Key Fields" },
		{ "AddRowListWithHDRField", "With-Key for Add Row List" },
		{ "AddRowListWithHDRFieldShort", "With-key for List" },
		{ "AddSKey", "Add Secondary Key" },
		{ "AddTabDialogComment", "* A 'tab' for another detail table will be added." },
		{ "AddTabDialogKeyComment", "* Specify DTL Table Keys according to HDR Table Keys. Initial value is the primary key of the DTL Table." },
		{ "AddTabDialogTitle", "Add Detail Tab" },
		{ "Alias", "Alias" },
		{ "Alignment", "Alignment" },
		{ "AlignmentMargin", "Alignment Margin" },
		{ "AllSubsystems", "(All Subsystems)" },
		{ "AndSoOn1", ""," and other " },
		{ "AndSoOn2", " elements." },
		{ "AskIfReplacing", "Specified file is existing. You may replace it?" },
		{ "AttributeName", "Attribute" },
		{ "AttributeValue", "Value" },
		{ "AutoConnect", "Get DB-Connection to edit" },
		{ "AutoNumberID", "Auto-No" },
		{ "AutoRowNumber", "Auto Row Number" },
		{ "AppServerName", "App.Server" },
		{ "BackToEdit", "Back to Editting" },
		{ "BarcodeType", "Barcode Type" },
		{ "BatchField", "Batch Field" },
		{ "BatchKey", "Batch Key" },
		{ "BatchKeyAbout", "*'Batch Key(s)' is the field which value is identical among the batch of detail table records. Specify physical fields on the primary table with ';' to separate them." },
		{ "BatchKeyField", "Key Field of Batch Processing" },
		{ "BatchRecordCallID", "Batch Function ID" },
		{ "BatchRecordCallMsg", "Check To Run" },
		{ "BatchTable", "Batch Table" },
		{ "BatchTableDialogTitle", "Edit Batch Table Config" },
		{ "BatchWithKeyField", "With-Key Field to Batch Table" },
		{ "Bookmark", "Add/Remove Bookmarks" },
		{ "Both", "Both" },
		{ "BrowseHelp", "XEAD Help" },
		{ "ButtonPositionComment", "0(Left End) - 6(Right End)" },
		{ "ButtonPositionComment0_5", "0(Left End) - 5(Right End)" },
		{ "CallFunction", "Call Function" },
		{ "CallPromptFunction", "Call ID" },
		{ "Cancel", "Cancel" },
		{ "CancelChanges", "Cancel changes" },
		{ "Caption", "Caption" },
		{ "CaptionErrorMessage", "Caption value contained invalid character '(' or ')' or ','.\nThey were removed from the value." },
		{ "CaptionLengthVariable", "Width Auto-Adjusted" },
		{ "CaseSensitive", "Case Sensitive" },
		{ "Changed", "Changed" },
		{ "ChangeLabel", "ID / Name" },
		{ "CheckContinueAdding", "Continue Adding"},
		{ "CheckFunctionsCalled", "Check Functions Called"},
		{ "CheckFunctionsCalledMessage1", "No errors found in relations of functions called."},
		{ "CheckFunctionsCalledMessage2", "The function is not called by any elements."},
		{ "CheckFunctionsCalledMessage3", "Function ID '"},
		{ "CheckFunctionsCalledMessage4", "' reffered in the script is not defined as a function in the system."},
		{ "CheckFunctionsCalledMessage5", "Function calling with ID'"},
		{ "CheckFunctionsCalledMessage6", "' is not defined as a function in the system."},
		{ "CheckFunctionsCalledMessage7", "Script '"},
		{ "CheckFunctionsCalledMessage8", "' contains function ID '"},
		{ "CheckFunctionsCalledMessage9", "' which is not defined as a function in the system."},
		{ "CheckFunctionsCalledMessage10", "Detail function is not specified whereas it's called by button to add."},
		{ "CheckFunctionsCalledMessage11", "Header function is not specified whereas it's called by button to process the header record."},
		{ "CheckUpdateOnly", "Update Only"},
		{ "ChooseAction", "Choose action to specify file to be processed" },
		{ "ChooseXeafFile", "Choose system definition file(*.xeaf) which is to be imported from." },
		{ "ClearValues", "Clear Val" },
		{ "Close", "Close" },
		{ "CloseNotSaving", "Discard" },
		{ "CloseSaving", "Save and Close" },
		{ "ColumnOnList", "Lists Including" },
		{ "Columns", "Columns" },
		{ "Comma", ", " },
		{ "Comment", "Comment" },
		{ "Commit", "Commit" },
		{ "Compress", "Compress" },
		{ "Connection", "DB Connection" },
		{ "ConsoleOption", "Console" },
		{ "ConsoleOptionYes", "Show" },
		{ "ConsoleOptionTimer", "Timer" },
		{ "ControlOptions", "Control Options" },
		{ "CopiedNameExt", "(Copy)" },
		{ "Copy", "Copy" },
		{ "CreateDefinition", "Create" },
		{ "CreateInSubsystem", "Create in Subsystem" },
		{ "CreateTableComment", "* Create Table Definitions one by one using SQL statement of CREATE TABLE. Only 'definitions' are created in this dialog. You need to create 'modules' afterward with definitions. Note that constraints of foreign keys are ignored and valid data types are those: CHAR,VARCHAR,INTEGER,SMALLINT,BIGINT,DOUBLE,DECIMAL,NUMERIC,REAL,DATE,TIME,TIMESTAMP" },
		{ "CreateTableDef", "Create Table Definitions" },
		{ "CreateTableStatement", "CREATE TABLE Statement" },
		{ "CreateTableTitle", "Create Table Definitions by CREATE TABLE Statement" },
		{ "Data", "Data" },
		{ "Database", "Database" },
		{ "DatabaseMain", "Main DB" },
		{ "DatabaseSub", "Sub DB" },
		{ "DataMessages", "Specify 'Where' and 'OrderBy' criteria as neccessary." },
		{ "DataName", "Data Name" },
		{ "DataOutput", "With EXCEL" },
		{ "DataSource", "Data Source" },
		{ "DataUtilityMessage1", "Input values and push 'Commit' button." },
		{ "DataUtilityMessage2", "The record has been updated successfully." },
		{ "DataUtilityMessage3", "Error: Another user has update this record before\nyou have read and tried to update." },
		{ "DataUtilityMessage4", "Error: Inserting failed because of the unique key duplication." },
		{ "DataUtilityMessage5", "The record has been inserted successfully." },
		{ "DataUtilityMessage6", "The record has been deleted successfully." },
		{ "DataUtilityMessage7", "The table has been compressed successfully." },
		{ "DateFormat", "Date Format" },
		{ "DBConnectMessage0", "XEAD Editor - Check Database Service" },
		{ "DBConnectMessage1", "It failed to connect to the database '" },
		{ "DBConnectMessage2", "'.\nCheck if the database service has been started." },
		{ "DBConnectMessage3", "Retry " },
		{ "DBConnectMessage4", "Skip connecting" },
		{ "Decimal", "Decimal" },
		{ "Delete", "Delete" },
		{ "DeleteCanceled", "Delete canceled." },
		{ "DeleteCheckMessage", "Ok to delete this row?" },
		{ "DeleteCheckTitle", "Check Delete" },
		{ "DeleteDefinitionAndModule", "Delete definition and module" },
		{ "DeleteDefinitionOnly", "Delete definition only" },
		{ "DeleteOperation", "Delete Operation" },
		{ "DeleteTableMessage", "Deleting the table module as well as its definition?" },
		{ "DeleteTableModule", "Deleting Table Module" },
		{ "Descent", "(Descent)" },
		{ "Descriptions", "Descriptions" },
		{ "DetailRowNumber", "Process last key field as row number" },
		{ "DTLField", "DTL Field" },
		{ "DTLFields", "DTL Fields" },
		{ "DTLFont", "DTL Font" },
		{ "DTLFunction", "DTL Function" },
		{ "DTLFunctionID", "DTL Function ID" },
		{ "DTLTable", "Detail Table" },
		{ "DTLTableID", "DTL Table ID" },
		{ "DTLTableKeys", "DTL Table Keys" },
		{ "DTLTabs", "DTL Tabs" },
		{ "Edit", "Edit" },
		{ "EditCode", "Edit Code" },
		{ "EditDetailTableKeyTitle", "Edit DTL Table Key" },
		{ "EditDetailTableKeyComment", "Specify unique keys of the header table and the detail table. Upper common fields must be as the same data type." },
		{ "EditKeyFieldsMessage", "Specify physical fields on the primary table with ';' to separate them." },
		{ "EditMode", "Edit Mode" },
		{ "EditOrderByMessage1", "Specify ID of fields on the table with ';' to separate them.\nBy putting '(D)' after fieldID"," it will work as DESCENT order field." },
		{ "EditOrderByMessage2", "Specify DataSource names with ';' to separate them.\nBy putting '(D)' after names"," it will work as DESCENT order field." },
		{ "EditorUser", "Editor User" },
		{ "EditRangeKeyMessage", "Specify a pair of the same type fields on the table with ';' to separate them." },
		{ "EditTableScriptTitle", "Edit Table Script" },
		{ "ElementName", "Name" },
		{ "ElementType", "Element" },
		{ "ErrorLog1", "Error Log named " },
		{ "ErrorLog2", " was generated." },
		{ "ErrorMessage1", "Error occured at [" },
		{ "ErrorMessage2", "]. Close XEAD Editor\nand refer to error log(xeadedt_err_....txt)" },
		{ "ErrorMessage3", "Field not found with ID'" },
		{ "ErrorMessage4", "'." },
		{ "ErrorMessage5", "Error: This is not a INTEGER field." },
		{ "ErrorMessage6", "Error: The first field is invalid." },
		{ "ErrorMessage7", "Error: The second field is invalid." },
		{ "ErrorMessage8", "Error: These are the same field." },
		{ "ErrorMessage9", "Error: Specify fields of the same type and length." },
		{ "ErrorMessage10", "Error: The first field must be part of the primary key." },
		{ "ErrorMessage11", "Field '" },
		{ "ErrorMessage12", "' is not valid or does not exist." },
		{ "ErrorMessage13", "Value specified is out of the range(" },
		{ "ErrorMessage14", ")." },
		{ "ErrorMessage15", "Error: Value specified is not a number" },
		{ "ErrorMessage16", "Error: Definition with ID '" },
		{ "ErrorMessage17", "' already exists." },
		{ "ErrorMessage18", "Error: Table definition with ID '" },
		{ "ErrorMessage19", "'\nalready exist under this or the other subsystem." },
		{ "ErrorMessage20", "Error: Deleting rejected as this subsystem has tables or functions." },
		{ "ErrorMessage21", "Error: Deleting rejected as tables or functions using this table exist." },
		{ "ErrorMessage22", "Error: This function is already on the menu." },
		{ "ErrorMessage23", "Error: No more room for another menu option." },
		{ "ErrorMessage24", "Margin values are invalid. They were reset as default(50;50;50;50)." },
		{ "ErrorMessage25", "Error: Command [" },
		{ "ErrorMessage26", "] failed.\n" },
		{ "ErrorMessage27", "Browsing Help failed." },
		{ "ErrorMessage28", "Saving file failed." },
		{ "ErrorMessage29", "Error: Deleting rejected as functions using this font exist." },
		{ "ErrorMessage30", "Error: Deleting rejected as least one element is required." },
		{ "ErrorMessage31", "Error: Deleting rejected as functions or join-tables or range-key reffering to this element exist." },
		{ "ErrorMessage32", "Error: Deleteing rejected as " },
		{ "ErrorMessage33", " fields are checked as refer fields.\nUncheck all of them on field list. If check boxes are inactive","\nput mouse cursor on them to popup their usage in the system." },
		{ "ErrorMessage34", "Error: Deleting rejected as this funcion is\na option of the menu '" },
		{ "ErrorMessage35", "'" },
		{ "ErrorMessage36", "Error: Deleting rejected as this funcion is used by function '" },
		{ "ErrorMessage37", "'" },
		{ "ErrorMessage38", "Error: It will lose consistency with new order of join tables.\nAll with-key values of each join table must be gained by preceding joins." },
		{ "ErrorMessage39", "Editting key definition is not allowed as\nfunctions or tables using this table exist." },
		{ "ErrorMessage40", "Error: Alias is needless for batch key field of the batch table." },
		{ "ErrorMessage41", "Error: Batch key(s) of the primary table is invalid. " },
		{ "ErrorMessage42", "Error: Batch key(s) of the batch table is invalid. " },
		{ "ErrorMessage43", "Error: Data type and size of coresponging fields of batch key must be the same. " },
		{ "ErrorMessage44", "Error: Alias is required for batch key field of the primary table. " },
		{ "ErrorMessage45", "Error: Numbers of fields are not matched between the primary table and the batch table. " },
		{ "ErrorMessage46", "Error: Alias is needless for 'With-Key Field'." },
		{ "ErrorMessage47", "Error: Field ID of 'With-Key Field' is invalid." },
		{ "ErrorMessage48", "Error: Field ID of 'With-Key for List' is invalid." },
		{ "ErrorMessage49", "Error: Data type and size of coresponging fields must be the same." },
		{ "ErrorMessage50", "Error: Field ID of 'With-Key for List' must be of a field or a join field of the header table." },
		{ "ErrorMessage51", "Error: Field ID of 'With-Key for List' must be with its alias." },
		{ "ErrorMessage52", "Error: Numbers of fields are not matched between those keys." },
		{ "ErrorMessage53", "Error: 'Return-From Field' is invalid." },
		{ "ErrorMessage54", "Error: 'Return-To Field' is invalid." },
		{ "ErrorMessage55", "Error: Data type and size of coresponging fields must be the same." },
		{ "ErrorMessage56", "Error: IDs of 'Return-To Field' must be with its alias." },
		{ "ErrorMessage57", "Error: IDs of 'Return-From Field' must be with its alias." },
		{ "ErrorMessage58", "Error: Numbers of fields are not matched between those keys." },
		{ "ErrorMessage59", "Error: Data Source of Fields-Putting '" },
		{ "ErrorMessage60", "' is invalid." },
		{ "ErrorMessage61", "Error: IDs of Fields-Putting must be with its alias." },
		{ "ErrorMessage62", "Error: Data Source of Fields-Putting-To '" },
		{ "ErrorMessage63", "' is invalid." },
		{ "ErrorMessage64", "Error: IDs of Fields-Putting-To must be with its alias." },
		{ "ErrorMessage65", "Error: Numbers of fields of Fields-Putting and Fields-Putting-To unmatch." },
		{ "ErrorMessage66", "Error: Numbers of fields of Fields-Getting and Fields-Getting-To unmatch." },
		{ "ErrorMessage67", "Error: Data Source of Fields-Getting '" },
		{ "ErrorMessage68", "' is invalid." },
		{ "ErrorMessage69", "Error: IDs of Fields-Getting must be with its alias." },
		{ "ErrorMessage70", "Error: Data Source of Fields-Getting-To '" },
		{ "ErrorMessage71", "' is invalid." },
		{ "ErrorMessage72", "Error: IDs of Fields-Getting-To must be with its alias." },
		{ "ErrorMessage73", "Error: Specify keys to process DTL records." },
		{ "ErrorMessage74", "Error: Number of DTL Table Keys must be more than HDR Table Keys." },
		{ "ErrorMessage75", "Error: Field ID '" },
		{ "ErrorMessage76", "' is invalid." },
		{ "ErrorMessage77", "Error: Data type and size of DTL table key field coresponging to HDR table key field must be the same." },
		{ "ErrorMessage78", "Error: Specify function ID." },
		{ "ErrorMessage79", "Error: Specify function type." },
		{ "ErrorMessage80", "Error: Specify function name." },
		{ "ErrorMessage81", "Error: The function with this ID already exists\nin this or another subsystem." },
		{ "ErrorMessage82", "Generating definition failed as the table specified is lacking primary key." },
		{ "ErrorMessage83", "Generating definition failed as the primary table specified is lacking primary key." },
		{ "ErrorMessage84", "Generating definition failed as the DTL table specified is lacking primary key." },
		{ "ErrorMessage85", "Error: Specify keys of HDR/DTL tables." },
		{ "ErrorMessage86", "Error: Specify physical fields on the primary table with ';' to separate them." },
		{ "ErrorMessage87", "Error: Field ID is invalid." },
		{ "ErrorMessage89", "Error: Specify physical fields on the DTL table with ';' to separate them." },
		{ "ErrorMessage90", "Error: Table ID is invalid." },
		{ "ErrorMessage91", "Error: This table is already joined. You can avoid\nduplication by specifying alias for this table." },
		{ "ErrorMessage92", "Error: Specify join-to/with keys." },
		{ "ErrorMessage93", "Error: Number of key fields are different." },
		{ "ErrorMessage94", "Error: Data type or size of corresponging key field is different." },
		{ "ErrorMessage95", "The first digit must be a single byte alphabet." },
		{ "ErrorMessage96", "Use single byte alpha-numeric characters." },
		{ "ErrorMessage97", "Error: Creating the table definition failed as the statement is invalid." },
		{ "ErrorMessage98", "The definition of table '" },
		{ "ErrorMessage99", "' has been created successfully." },
		{ "ErrorMessage100", "Error: Creating the table definition failed as table '" },
		{ "ErrorMessage101", "' already exists in this or another subsystem." },
		{ "ErrorMessage102", "Error: The field '" },
		{ "ErrorMessage103", "' has invalid data type(" },
		{ "ErrorMessage104", "). This field was eliminated from the table definition." },
		{ "ErrorMessage105", "Error: Character '_' is not allowed for table ID." },
		{ "ErrorMessage106", "Error: Specify keys to process HDR records." },
		{ "ErrorMessage107", "Error: Deleting rejected as tables targetting to this database exist." },
		{ "ErrorMessage108", "This operation is not permitted as any of db-connections are invalid." },
		{ "ErrorMessage109", "No need to include tableID in fieldID." },
		{ "ErrorMessage110", "Field ID of 'Upper Keys' in invalid." },
		{ "ErrorMessage111", "'Upper Keys' and PK of the header table is not corresponding about its data type." },
		{ "ErrorMessage112", "Field ID of 'Child Keys' in invalid." },
		{ "ErrorMessage113", "'Child Keys' and PK of the header table is not corresponding." },
		{ "ErrorMessage114", "Size of structure view is invalid. Value is set as default." },
		{ "ErrorMessage115", "Field ID must be a single value." },
		{ "ErrorMessage116", "Field value list or icon list is invalid." },
		{ "ErrorMessage117", "Field ID of order-by field is invalid." },
		{ "EventAC", "AfterC" },
		{ "EventAD", "AfterD" },
		{ "EventAR", "AfterR" },
		{ "EventAU", "AfterU" },
		{ "EventBC", "BeforeC" },
		{ "EventBD", "BeforeD" },
		{ "EventBR", "BeforeR" },
		{ "EventBU", "BeforeU" },
		{ "EventReferAR", "After Reading All Join Tables" },
		{ "EventReferAR1", "After Reading Table '" },
		{ "EventReferAR2", "'" },
		{ "EventReferAS", "After Processing detail records" },
		{ "EventReferBR", "Before Reading All Join Tables" },
		{ "EventReferBR1", "Before Reading Table '" },
		{ "EventReferBR2", "'" },
		{ "ExchangeParms", "EXC" },
		{ "Execute", "Execute" },
		{ "ExecuteWhen", "Execute When" },
		{ "ExecuteWhenJoin", "Execute When (Join Table)" },
		{ "Exit", "Exit" },
		{ "ExitMessage", "Save changes to exit?" },
		{ "ExitNotSaving", "Discard" },
		{ "ExitSaving", "Save and Exit" },
		{ "ExtentionInvalid", "Extention of the file is invalid." },
		{ "F3ToScan", "F3:Scan" },
		{ "FailedToParse", "It failed to parse xead file specified. Check format of file." },
		{ "Field", "Field" },
		{ "FieldAccountDate", "Acc.Date" },
		{ "FieldBoolean", "Boolean" },
		{ "FieldDialNo", "Tel.No" },
		{ "FieldExtType", "Ext-Type" },
		{ "FieldFiscalYear", "Fiscal Year" },
		{ "FieldID", "Field ID" },
		{ "FieldImageFile", "Image File" },
		{ "FieldKana", "Kana" },
		{ "FieldKanji", "Kanji" },
		{ "FieldKubunID", "Kubun" },
		{ "FieldMargin", "Margin" },
		{ "FieldMonthSeq", "Fiscal M.No" },
		{ "FieldName", "Field Name" },
		{ "FieldRows", "Rows" },
		{ "Fields", "Fields" },
		{ "FieldSize", "Size" },
		{ "FieldsToExchangeComment", "* Specify field IDs(with alias) to exchange with the prompt function. Use ';' to separate IDs." },
		{ "FieldsToExchangeDialog", "Fields to Exchange with Prompt Function" },
		{ "FieldsToGet", "Fields Getting" },
		{ "FieldsToGetTo", "Fields Getting to" },
		{ "FieldsToPut", "Fields Putting" },
		{ "FieldsToPutTo", "Fields Putting to" },
		{ "FieldType", "Type" },
		{ "FieldURL", "URL" },
		{ "FieldUsageInScript1", "Variant Field in Script '" },
		{ "FieldUsageInScript2", "'" },
		{ "FieldUsageInScript3", "Variant Field in Script" },
		{ "FieldUsageMessage", "This field is used by those elements.\n" },
		{ "FieldUsageToKeyField", "To-Key Field of Join Table" },
		{ "FieldUsageWithKeyField1", "With-Key Field to Join Table(" },
		{ "FieldUsageWithKeyField2", ")" },
		{ "FieldValueList", "Value List" },
		{ "FieldWidth", "Width" },
		{ "FieldYearMonth", "Year Month" },
		{ "FieldZipNo", "ZIP No" },
		{ "FieldZipAdrs", "Link Address" },
		{ "File", "File" },
		{ "FileSpecifiedNotFound", "File with specified name and the valid extention is not found." },
		{ "FilterOfDetailList", "Filter of Detail List" },
		{ "FilterOption", "Filter Option" },
		{ "Filters", "Filters" },
		{ "FixedWhere", "Fixed Where" },
		{ "FixedWhereDTL", "DTL Fixed Where" },
		{ "FixedWhereHDR", "HDR Fixed Where" },
		{ "Font", "Font" },
		{ "FontSize", "Size" },
		{ "FontStyle", "Style" },
		{ "FontStyleBold", "Bold" },
		{ "FontStyleBoldItalic", "BoldItalic" },
		{ "FontStyleItalic", "Italic" },
		{ "FontStyleNormal", "Normal" },
		{ "FontStyleUnderlined", "Underlined" },
		{ "FormatVersionError1", "Format Version of this XEAD Editor content file is " },
		{ "FormatVersionError2", ". Format Version this application can handle with is upto " },
		{ "FormatVersionError3", ". Please use the latest program." },
		{ "FunctionDefinition", "Function" },
		{ "FunctionDefinitions", "Functions" },
		{ "FunctionID", "Function ID" },
		{ "FunctionKeyNo", "Function Key No" },
		{ "FunctionKeys", "Function Keys" },
		{ "FunctionList", "Function List" },
		{ "FunctionName", "Function Name" },
		{ "FunctionsWhereUsed", "Where-Used" },
		{ "FunctionType", "Function Type" },
		{ "FunctionTypeXF000", "XF000 Script Launcher" },
		{ "FunctionTypeXF010", "XF010 Script Launcher #1" },
		{ "FunctionTypeXF100", "XF100 Inquiry List" },
		{ "FunctionTypeXF110", "XF110 Update List" },
		{ "FunctionTypeXF200", "XF200 Single CRUD" },
		{ "FunctionTypeXF210", "XF210 Single Update" },
		{ "FunctionTypeXF290", "XF290 Single Print" },
		{ "FunctionTypeXF300", "XF300 HDR/DTL Inquiry" },
		{ "FunctionTypeXF310", "XF310 HDR/DTL Update" },
		{ "FunctionTypeXF390", "XF390 HDR/DTL Print" },
		{ "Function/AddRowListButton", "Function / Add-Row-List Button" },
		{ "Function/AddRowListField", "Function / Add-Row-List Field" },
		{ "Function/BatchField", "Function / Batch Field" },
		{ "Function/Button", "Function / Button" },
		{ "Function/DTLButton", "Function / DTL Button" },
		{ "Function/DTLField", "Function / DTL Field" },
		{ "Function/DTLTab", "Function / DTL Tab" },
		{ "Function/Field", "Function / Field" },
		{ "Function/Filter", "Function / Filter" },
		{ "Function/HDRField", "Function / HDR Field" },
		{ "Function/HDRPhrase", "Function / HDR Phrase" },
		{ "Function/Phrase", "Function / Phrase" },
		{ "GenerateList", "Output" },
		{ "HDRData", "HDR Data" },
		{ "HDRField", "HDR Area Field" },
		{ "HDRFields", "HDR Fields" },
		{ "HDRFunctionID", "HDR Function ID" },
		{ "HDRTable", "HDR Table" },
		{ "HDRTableKeys", "HDR Table Keys" },
		{ "Height", "Height" },
		{ "Help", "Help" },
		{ "HitCount", "Hit" },
		{ "ID", "ID" },
		{ "ImageFolder", "Image Folder" },
		{ "Import", "Import" },
		{ "ImportCsv", "Import CSV-formatted data" },
		{ "ImportCsvMessage1", "Importing csv has completed with " },
		{ "ImportCsvMessage2", " record(s) inserted and " },
		{ "ImportCsvMessage3", " record(s) skipped as their key already exist." },
		{ "ImportCsvMessage4", "ERROR: CSV data contains inconsistency." },
		{ "ImportMessage1", "* Press Import-button after checking any tables or functions to be imported. If ID of the element being imported is existing in another subsystem than the one to be imported into, process type of the element is shown as 'UNMATCH'. Those elements are not imported even if checked." },
		{ "ImportMessage2", "merged successfully."},
		{ "ImportMessage3", "replaced successfully."},
		{ "ImportMessage4", "added successfully."},
		{ "ImportMessage5", "importing skipped as irregularity containning."},
		{ "ImportMessage6", "importing skipped as ID of the element existing in another subsystem than the one selected."},
		{ "ImportMessage7", "Join table is invalid."},
		{ "ImportMessage8", "Join table key is invalid."},
		{ "ImportMessage9", "Join field is invalid."},
		{ "ImportMessage10", "Primary key is not allowed to alter."},
		{ "ImportMessage11", "Primary table is invalid."},
		{ "ImportMessage12", "Primary table key is invalid."},
		{ "ImportMessage13", "Order-By of rows is invalid."},
		{ "ImportMessage14", "Detail field is invalid."},
		{ "ImportMessage15", "Filter field is invalid."},
		{ "ImportMessage16", "Batch table is invalid."},
		{ "ImportMessage17", "Batch key is invalid."},
		{ "ImportMessage18", "Field is invalid."},
		{ "ImportMessage19", "Header table is invalid."},
		{ "ImportMessage20", "Header table key is invalid."},
		{ "ImportMessage21", "Header field is invalid."},
		{ "ImportMessage22", "Detail table is invalid."},
		{ "ImportMessage23", "Detail table key is invalid."},
		{ "ImportMessage24", "Detail field is invalid."},
		{ "ImportMessage25", "Add-Row-List table is invalid."},
		{ "ImportMessage26", "Add-Row-List table key is invalid."},
		{ "ImportMessage27", "Order-By of Add-Row-List is invalid."},
		{ "ImportMessage28", "Exchange-List of Add-Row-List is invalid."},
		{ "ImportMessage29", "Add-Row-List field is invalid."},
		{ "ImportMessage30", "Function-Type is invalid."},
		{ "ImportMessage31", "Phrase Font is invalid."},
		{ "ImportMessage32", "Table Font is invalid."},
		{ "ImportMessage33", "Database is invalid."},
		{ "ImportMessage34", "Structure table is invalid."},
		{ "ImportMessage35", "Config of structure node text is invalid."},
		{ "ImportMessage36", "Control field of structure node icon is invalid."},
		{ "ImportDialogTitle1", "Import Frim System Definition File " },
		{ "ImportDialogTitle2", "" },
		{ "Index", "Index" },
		{ "InitialMessage", "Initial Message" },
		{ "InitialReadCount", "Initial Read Count" },
		{ "InitialValue", "Initial Value" },
		{ "JoinField", "Join Field" },
		{ "JoinFields", "Join Fields" },
		{ "JoinOrderBy", "Join Order-By" },
		{ "JoinRecordExist", "Record Exist" },
		{ "JoinRecordOptional", "Optional" },
		{ "JoinTable", "Join Table" },
		{ "JoinTables", "Join Tables" },
		{ "JoinTableWithAlias", "Join Table"," Alias=" },
		{ "JoinToKeys", "Join-To Keys" },
		{ "JoinWithKeys", "Join-With Keys" },
		{ "Jump", "Jump" },
		{ "JumpTo1", "Jump to \"" },
		{ "JumpTo2", "\"" },
		{ "JumpToBookmark", "Jump to bookmark" },
		{ "KeyFieldOfDTLTable", "Key Field of Detail Table" },
		{ "KeyFieldOfHDRTable", "Key Field of Header Table" },
		{ "KeyFieldOfPrimaryTable", "Key Field of Primary Table" },
		{ "KeyFields", "Key Fields" },
		{ "Keys", "Keys" },
		{ "KeyType", "Key Type" },
		{ "KeywordList", "Keyword List" },
		{ "Launch", "Launch System" },
		{ "LaunchSystemTitle", "Save changes in current file before launching system?" },
		{ "LayoutHorizontal", "Horizontal" },
		{ "LayoutOption", "Layout Option" },
		{ "LayoutVertical", "Vertical" },
		{ "Lines", "lines" },
		{ "List", "List" },
		{ "ListBox", "ListBox" },
		{ "ListCsv", "List CSV" },
		{ "ListingOperations", "Listing Operations" },
		{ "ListLog", "List Log" },
		{ "ListLogComment", "* Only those table operations executed in sessions by XEAD Driver are listed. And also operations with 'WHERE' criteria values are matching or partial to the key values of the specified record." },
		{ "ListLogMessage1", " log(s) found to be listed. Select the row to see details." },
		{ "ListLogMessage2", "No log found to be listed." },
		{ "ListLogTitle", "List Log of Table Operations" },
		{ "ListTable", "List Table" },
		{ "LoginScript", "Login Script" },
		{ "LoginTime", "Login Time" },
		{ "MainDB", "Main DB" },
		{ "MainMenuEdit", "Edit(E)" },
		{ "MainMenuFile", "File(F)" },
		{ "MainMenuHelp", "Help(H)" },
		{ "MainMenuScan", "Scan(S)" },
		{ "MainMenuTools", "Tools(T)" },
		{ "Menu", "Menu" },
		{ "Menu/Option", "Menu / Option" },
		{ "MenuDefinitions", "Menus" },
		{ "MenuHelpURL", "Help URL" },
		{ "MenuID", "Menu ID" },
		{ "MenuList", "Menu List" },
		{ "MenuName", "Menu Name" },
		{ "MenuOption", "Menu Option" },
		{ "MenuOptionName", "Menu Option Name" },
		{ "MenuOptions", "Menu Options" },
		{ "MenuTree", "Menu Tree" },
		{ "Message", "Message" },
		{ "MinusRejectMessage", "Minus expression is ignored." },
		{ "ModuleCheck", "Module Check" },
		{ "ModuleCheckMessage1", "Unmatched data-type or size of the field '" },
		{ "ModuleCheckMessage2", "'.\n. . . Its type on the definition is " },
		{ "ModuleCheckMessage3", ", whereas " },
		{ "ModuleCheckMessage4", " on the module.\n" },
		{ "ModuleCheckMessage5", "Field '" },
		{ "ModuleCheckMessage6", "' is nullable on the definition, whereas not-null on the module.\n" },
		{ "ModuleCheckMessage7", "Field '" },
		{ "ModuleCheckMessage8", "' is not-null on the definition, whereas nullable on the module.\n" },
		{ "ModuleCheckMessage9", "Field '" },
		{ "ModuleCheckMessage10", "' does not exis on the module.\n" },
		{ "ModuleCheckMessage11", "Update-counter field '" },
		{ "ModuleCheckMessage12", "' on the module is not INTEGER but " },
		{ "ModuleCheckMessage13", ".\n" },
		{ "ModuleCheckMessage14", "Update-counter field '" },
		{ "ModuleCheckMessage15", "' does not exist on the module.\n" },
		{ "ModuleCheckMessage16", "The physical field '" },
		{ "ModuleCheckMessage17", "' exists on the module but has no definition.\n" },
		{ "ModuleCheckMessage18", "Unique key '" },
		{ "ModuleCheckMessage19", "' exists on the module but has no definition.\n" },
		{ "ModuleCheckMessage20", "The index '" },
		{ "ModuleCheckMessage21", "' of the module does not exist on the defintion.\n" },
		{ "ModuleCheckMessage22", "The definitions of the primary key are different. Its '" },
		{ "ModuleCheckMessage23", "' on the definition, whereas '" },
		{ "ModuleCheckMessage24", "' on the module.\nNote that you have to delete and re-create the module to modify the primary key if it already exists.\n" },
		{ "ModuleCheckMessage25", "The secondary key '" },
		{ "ModuleCheckMessage26", "' does not exist on the module.\n" },
		{ "ModuleCheckMessage27", "The index '" },
		{ "ModuleCheckMessage28", "' does not exist on the module. It's worth while trying modifying module.\n" },
		{ "ModuleCheckMessage29", "The primary key is not defined, whereas the module has one as '" },
		{ "ModuleCheckMessage30", "'. \n" },
		{ "ModuleCheckMessage31", "The table module does not exist." },
		{ "ModuleCheckMessage32", ". . . Complete definitions and create table module." },
		{ "ModuleCheckMessage33", ". . . You need to delete and re-create the module." },
		{ "ModuleCheckMessage34", ". . . Note that field(s) on the table module might be removed all with its data if you execute 'Modify Module' to modify field attributes. And also note that sometimes you have to try more than once to complete modifying module because of priority of attributes to be modified. If you want to remove a secondary uniqu key from tables, you need to use SQL console. Refer to HELP for details." },
		{ "ModuleCheckMessage35", "* The table module matches to the definition. No need to modify the module." },
		{ "ModuleCheckMessage36", "The table module will be modified according to\nthe current definition. Sure to execute?" },
		{ "ModuleCheckMessage37", "It failed to modify the table module.\n\n" },
		{ "ModuleCheckMessage38", "Creating table module is not allowed as it contains no primary key." },
		{ "ModuleCheckMessage39", "The table module will be created according to the definition.\nNote that you have to delete the module to modify the primary key.\nSure to create?" },
		{ "ModuleCheckMessage40", "It failed to create the table module.\n\n" },
		{ "ModuleCheckMessage41", "The table module will be\ndeleted. Sure to execute?" },
		{ "ModuleCheckMessage42", "It failed to delete the table module." },
		{ "ModuleCheckMessage43", "* The table module has been created successfully." },
		{ "ModuleCheckMessage44", "* The table module is now sychronized to the definition. Modify table data if required." },
		{ "ModuleCheckMessage45", "* The table module matches to the definition. No need to alter the module although it has foreign-key constraint(s) which is not required by XEAD Driver." },
		{ "ModuleCheckMessage46", "Type or length of field(s) of the primary key is different." },
		{ "ModuleCreate", "Create Module" },
		{ "ModuleDelete", "Delete Module" },
		{ "ModuleModify", "Modify Module" },
		{ "Name", "Name" },
		{ "NameDialogTitle", "XEAD Editor - Specify folder and file name" },
		{ "NewScript", "New Script" },
		{ "NewTab", "New Tab" },
		{ "Next", "Next" },
		{ "No", "No" },
		{ "NoCaption", "No Caption" },
		{ "NoFieldsLeftToBeAdded", "No fields left to be added." },
		{ "None", "None" },
		{ "NonEditable", "Not Editable" },
		{ "NumberFormatError", "Decimal point is invalid." },
		{ "Nullable", "Nullable" },
		{ "NullCheckMessage", "Null is not allowed." },
		{ "Open", "Open" },
		{ "OpenExistintContent", "Open existing content file" },
		{ "OpenMessage", "Current file has been changed. Save changes to open file?" },
		{ "OpenNotSaving", "Open without Saving" },
		{ "OpenSaving", "Save and Open" },
		{ "OpenXEAFFile", "Open existing xeaf file." },
		{ "OptionalList", "Optional List" },
		{ "OptionName", "Option Name" },
		{ "OrderByFields", "Order By" },
		{ "OrderByOfDetailList", "Order-By Field of Detail List" },
		{ "OrderByOfJoinTable", "Order-By Field of Join Table" },
		{ "Output", "Output" },
		{ "OutputFolder", "Output Folder" },
		{ "PageDirection", "Page Direction" },
		{ "PageMargins", "Margins(L,R,T,B)" },
		{ "PageNo", "With Page No" },
		{ "PageSize", "Page Size" },
		{ "PanelSize", "Panel Size" },
		{ "Parameters", "Parameters" },
		{ "Password", "Password" },
		{ "Paste", "Paste" },
		{ "PasteChild", "Paste child-node" },
		{ "PhraseBlock", "Phrase Block" },
		{ "PhraseFormula", "Phrase Formula" },
		{ "PhraseSpacingAfter", "Spacing After" },
		{ "PhysicalField", "Physical Field" },
		{ "PKey", "Primary Key" },
		{ "Pos_short", "Pos." },
		{ "Position", "Position" },
		{ "Previous", "Previous" },
		{ "PrimaryTable", "Primary Table" },
		{ "PrintFont", "Print Font" },
		{ "ProcessType", "Process" },
		{ "Prompt", "Prompt" },
		{ "PrompterFunction", "Function Prompter" },
		{ "PrompterFunctionExchange", "Exchanged field of a prompter" },
		{ "PrompterList", "List Prompter" },
		{ "RangeKeyField", "Range Key Field" },
		{ "RangeKeys", "Range Keys" },
		{ "ReadCheckMessage", " records are selected. Choose option to continue." },
		{ "ReadCheckTitle", "Check Record Count" },
		{ "ReadCountMessage", " records are found with criteria specified." },
		{ "ReadEmptyMessage", "The table has no record." },
		{ "ReadEnd", "Stop Reading" },
		{ "ReadMore", "Read More" },
		{ "ReadNoneMessage", "No record found with criteria specified." },
		{ "ReadOnlyWarning1", "Specified is a Read-Only file. Note that you" },
		{ "ReadOnlyWarning2", "can not save what you have editted with XEAD Editor." },
		{ "Redo", "Redo changes in node" },
		{ "Remarks", "Remarks" },
		{ "RemoveRow", "Remove Row" },
		{ "ReplaceAllSelected", "Replace all selected" },
		{ "ReplaceFile", "Replace" },
		{ "ReplaceSaveMessage", "Save what you have processed?" },
		{ "ReplaceSaveTitle", "XEAD Editor - Save Replacing" },
		{ "RequiredList", "Required List" },
		{ "Result", "Result" },
		{ "RetrieveLog", "Retrieve Log" },
		{ "Return", "Return" },
		{ "ReturnFields", "Return Fields" },
		{ "RowAction", "When Row Selected" },
		{ "RowActionCall", "Call Function" },
		{ "RowActionReturn", "Return Keys" },
		{ "RowNoWidth", "Row No Width" },
		{ "Save", "Save" },
		{ "SaveAs", "Save As" },
		{ "SaveAsThis", "Save As This Name" },
		{ "SaveChanges", "Save Changes" },
		{ "SaveChangesTitle", "XEAD Editor - Saving Changes" },
		{ "Scan", "Scan" },
		{ "ScanDialogComment1", "Only those elements you can edit by XEAD Editor are scanned. Elements like IDs and alias of join tables are not scanned as they are not edittable." },
		{ "ScanDialogComment2", " elements with " },
		{ "ScanDialogComment3", " of strings were found. Select any row to see detail value." },
		{ "ScanDialogComment4", "None of elements was found with the string." },
		{ "ScanDialogComment5", " elements with " },
		{ "ScanDialogComment6", " strings were replaced." },
		{ "ScanDialogTitle", "Scan/Replace String" },
		{ "ScanMessage", "Current file has been changed. Saving required to scan." },
		{ "ScanRange", "Scanning" },
		{ "ScanReplace", "Scan/Replace String" },
		{ "ScanStart", "Start Scan" },
		{ "ScanString", "Scanning" },
		{ "ScanStringInScript", "String scanned (F3 to start scan from cursor position)" },
		{ "ScanStringInScriptMessage", "Not found." },
		{ "ScanStringReplacedTo", "Replacing" },
		{ "Script", "Script" },
		{ "ScriptChangesMessage", "Save Changes in the script?" },
		{ "ScriptFunctions", "Script Functions" },
		{ "ScriptNotesTitle1", "<< Native Field Variants List >>" },
		{ "ScriptNotesTitle2", "\n\n<< Join Field Variants List >>" },
		{ "ScriptNotesTitle3", "\n\n<< Legends of Variant Name >>\n[TableID]_[FieldID].value : Field value\n[TableID]_[FieldID].oldValue : Field value before update(read-only)\n[TableID]_[FieldID].valueChanged : Whether value has been changed or not(read-only:true,false)\n[TableID]_[FieldID].color : Font Color(black,green,blue,red,orange)\n[TableID]_[FieldID].editable : Editability(true,false)\n[TableID]_[FieldID].error : Error message\n( You can also use 'session' and 'instance (of function)'.\nRefer to HELP for details.)" },
		{ "ScriptNotesVFMark", "(V/F) " },
		{ "Scripts", "Scripts" },
		{ "Sel", "Sel" },
		{ "SelectContent", "XEAD Editor - Select Content File" },
		{ "SelectFile", "Select file and open" },
		{ "SelectFromList", "( Select from the list )" },
		{ "SelectList", "Select-List" },
		{ "SessionNo", "Session No" },
		{ "SizeAuto", "Auto Sizing" },
		{ "SizeFull", "Full" },
		{ "SizeSpecified", "Specified(w,h)" },
		{ "SKey", "Secondary Key" },
		{ "SpecifyName", "Specify file name again" },
		{ "SpecifyNewID", "Specify ID of this element to add." },
		{ "SpecifyNewIDOfTable", "Specify ID of this table to add. Note that\njoin-table/fields and scripts are not copied." },
		{ "SqlCommitF9", "Commit F9" },
		{ "SqlConsole", "SQL Console" },
		{ "SqlConsoleComment", "* You can execute RDBMS embedded procedures as well as SQL statements here. But executing CREATE TABLE statement is almost meaningless. as the table definition for XEAD Editor will not be generated. Use 'Create Table Definitions' of Tool menu to create table definitions and modules.\n" },
		{ "SqlConsoleMessage1", ". . . Committing succeded.\n(" },
		{ "SqlConsoleMessage2", "Operation failed." },
		{ "Status", "Status" },
		{ "StrNodeIconField", "Structure Node Icon Field" },
		{ "StrNodeText", "Structure Node Text Field" },
		{ "StrRootText", "Structure Root Icon Field" },
		{ "StrUpperKeyField", "Structure Upper Key Field" },
		{ "StrChildKeyField", "Structure Child Key Field" },
		{ "StructureChildKeys", "Child Keys" },
		{ "StructureNodeDefaultIcon", "Default Icon" },
		{ "StructureNodeIcons", "Node Icons" },
		{ "StructureNodeIconsComment", "Control field is one of physical fields of the header tabel. Number of Icons and field values separated by ';' must be corresponding each other." },
		{ "StructureNodeIconsFieldID", "Controle Field" },
		{ "StructureNodeIconsFieldValues", "Field Values" },
		{ "StructureNodeIconsList", "Icon List" },
		{ "StructureNodeIconsTitle", "Config Structure Node Icons" },
		{ "StructureNodeText", "Node Text" },
		{ "StructureNodeTextRemarks", "Specify physical datasouces on the HDR table or structure table\nwith ';' to separate them.Use quotation(') to put fixed string value." },
		{ "StructureOrderBy", "OrderBy" },
		{ "StructureRootText", "Root Text" },
		{ "StructureRootTextRemarks", "Specify physical fieldID on the HDR table with ';' to separate them.\nUse quotation(') to put fixed string value." },
		{ "StructureTable", "Structure Table" },
		{ "StructureTableComment", "'Upper Keys' and 'Child Keys' are corresponding to PK of the parent table." },
		{ "StructureTableTitle", "Config Structure Table" },
		{ "StructureUpperKeys", "Upper Keys" },
		{ "StructureView", "Structure Tree" },
		{ "StructureViewWidth", "Tree View Width" },
		{ "Subsystem", "Subsystem" },
		{ "SubsystemDescriptions", "Subsystems" },
		{ "SubsystemFunctions", "F" },
		{ "SubsystemID", "Subsystem ID" },
		{ "SubsystemImportingFrom", "Subsystem Importing From" },
		{ "SubsystemImportingInto", "Importing Into" },
		{ "SubsystemList", "Subsystem List" },
		{ "SubsystemName", "Subsystem Name" },
		{ "SubsystemRemarks", "Subsystem Descriptions" },
		{ "SubsystemTables", "T" },
		{ "System", "System" },
		{ "SystemCalendar", "Calendar" },
		{ "SystemDatabaseConfig", "Database Config" },
		{ "SystemOtherConfig", "Other" },
		{ "SystemDefinition", "System Definition" },
		{ "SystemDescriptions", "System" },
		{ "SystemExchangeRateAnnual", "Annual Cur.Rate" },
		{ "SystemExchangeRateMonthly", "Monthly Cur.Rate" },
		{ "SystemName", "System Name" },
		{ "SystemNameImporting", "System Importing From" },
		{ "SystemNumbering", "Numbering" },
		{ "SystemRemarks", "Descriptions" },
		{ "SystemSession", "Session" },
		{ "SystemSessionDetail", "Session Detail" },
		{ "SystemTax", "Tax" },
		{ "SystemUser", "User" },
		{ "SystemUserVariants", "User Variants" },
		{ "SystemVariants", "Sys. Variants" },
		{ "SystemVersion", "Version" },
		{ "TabbedFields", "Tabbed Fields" },
		{ "Table", "Table" },
		{ "TableDefinition", "Table Definition" },
		{ "TableDefinitions", "Tables" },
		{ "Table/Field", "Table / Field" },
		{ "Table/Script", "Table / Script" },
		{ "TableID", "Table ID" },
		{ "TableList", "Table List" },
		{ "TableModuleCheck", "Module Check" },
		{ "TableName", "Table Name" },
		{ "TableOperation", "Table Operation" },
		{ "TableUsageInScript1", "Operated in Script '" },
		{ "TableUsageInScript2", "' (" },
		{ "TableUsageInScript3", ")" },
		{ "TableUsageInScript4", "Operated in Script (" },
		{ "Text", "Text" },
		{ "TimerDefault", "Default Time" },
		{ "TimerMessage", "Message" },
		{ "TipsFunction", "You can change the subsystem of functions. Drag and drop the tree node of function into function list of the target subsystem." },
		{ "TipsMenu", "Drag and drop the tree node of function into this list.\nThe Function will be a menu option of this menu." },
		{ "TipsTable", "You can change the subsystem of tables. Drag and drop the tree node of table into table list of the target subsystem." },
		{ "TipsTitle", "Hint to Edit" },
		{ "TipsToEdit", "Tips to edit" },
		{ "Tools", "Tool" },
		{ "Type", "Type" },
		{ "TypeOptions", "Type Options" },
		{ "Undo", "Undo changes in node" },
		{ "Update", "Update" },
		{ "UpdateCounter", "Update Counter" },
		{ "UpdateList", "Update-List" },
		{ "UpdateMessage", "Execute Message" },
		{ "UsageBatchFieldPrompter", "Batch Field Prompter" },
		{ "UsageColumnPrompter", "Column Prompter" },
		{ "UsageDTLFunction", "DTL Function" },
		{ "UsageFieldPrompter", "Field Prompter" },
		{ "UsageHDRFunction", "HDR Function" },
		{ "UsageLaunchedAfterInsert", "Launched After Insert" },
		{ "UsageLaunchedByBatchRecord", "Launched By Batch Record" },
		{ "UsageLaunchedByFunctionKey", "Launched By Function Key" },
		{ "UsageLaunchedByRow", "Launched By Detail Rows" },
		{ "UsageLaunchedInScript", "Launched In Script" },
		{ "User", "User" },
		{ "UserID", "User ID" },
		{ "ValueSpecified", "Value" },
		{ "VariantNameOnScript", "Variant name on script" },
		{ "Virtual", "Virtual" },
		{ "WarningMessage1", "Warning: Data source name of this join field\nduplicates with fields of the batch table." },
		{ "WarningMessage2", "Warning: Data source name of this join field\nduplicates with fields of the primary table." },
		{ "WarningMessage3", "Warning: Data source name of this join field\nduplicates with fields of the DTL table." },
		{ "WarningMessage4", "Warning: Data source name of this join field\nduplicates with fields of the HDR table." },
		{ "WelcomePageURL", "Welcome Page" },
		{ "WhereUsed", "Where Used" },
		{ "WhereUsedForm", "Where-Used Form" },
		{ "WhereUsedTable", "Where-Used Table" },
		{ "Width", "Width" },
		{ "WidthRate", "Width Rate" },
		{ "WithTotal", "With Total" },
		{ "XLSComment", "*These rows are filtered or ordered by those criteriaÅF" },
		{ "XLSErrorMessage", "IOException of EXCEL data. Refer to session log for details." },
		{ "XLSFontDTL", "Times New Roman" },
		{ "XLSFontHDR", "Arial" },
		{ "Yes", "Yes" }
	};

	public Object[][] getContents() {
		return contents;
	}
}
