package xeadEditor;

/*
 * Copyright (c) 2017 WATANABE kozo <qyf05466@nifty.com>,
 * All rights reserved.
 *
 * This file is part of X-TEA Editor.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the XEAD Project nor the names of its contributors
 *       may be used to endorse or promote products derived from this software
 *       without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

public class Res extends java.util.ListResourceBundle {
	private static final Object[][] contents = new String[][]{
		{ "About", "About X-TEA Editor" },
		{ "AcceptMinus", "Accept Minus" },
		{ "Action", "Action" },
		{ "ActionAddBlankRow", "Add a blank row" },
		{ "ActionAddRows", "Add rows" },
		{ "ActionAddRowWithSelected", "Add rows with selected" },
		{ "ActionAfterInsert", "After Insert" },
		{ "ActionBackToSelectList", "Back to Select-List" },
		{ "ActionCall", " is to be called" },
		{ "ActionCallDTLFunctionToAdd", "Call DTL Function to Add" },
		{ "ActionCallFunction", "Calling" },
		{ "ActionCallHDRFunction", "Call HDR Function" },
		{ "ActionCallToAddRows", "Call to add rows" },
		{ "ActionDelete", "Delete" },
		{ "ActionDeleteHDR", "Delete HDR Record" },
		{ "ActionExit", "Exit" },
		{ "ActionGoToCopyMode", "Go to Copy-Mode" },
		{ "ActionGoToEditMode", "Go to Edit-Mode and update" },
		{ "ActionGoToUpdateList", "Go to Update-List" },
		{ "ActionOutputEXCEL", "Output into EXCEL" },
		{ "ActionRemoveRow", "Remove the Row" },
		{ "ActionReturnNull", "Return Null Key" },
		{ "ActionUpdate", "Update with Editted Values" },
		{ "Add", "Add" },
		{ "AddChild", "Add child-node" },
		{ "AddFields", "Select Fields to be Added" },
		{ "AddFunction", "Add a Function" },
		{ "AddIndex", "Add Index" },
		{ "AddIndexMessage", "Specify physical fields with ';' to separate them.\nBy putting '(D)' after fieldID"," it will work as DESCENT order field." },
		{ "AddJoinTable", "Add Join Table" },
		{ "AddJoinTableMessage1", "Specify ID and alias(if neccessary) of table to be joined." },
		{ "AddJoinTableMessage2", "Specify field IDs of " },
		{ "AddJoinTableMessage3", " to Join-To keys, and corresponding data source names of " },
		{ "AddJoinTableMessage4", " to Join-With keys. You can use ';' to separate IDs." },
		{ "AddKeyMessage", "Choose field to put into key definition." },
		{ "AddMode", "Add Mode" },
		{ "AddNewFields", "Add New Fields" },
		{ "AddNewMenus", "Add New Menus" },
		{ "AddNewSubsystems", "Add New Subsystems" },
		{ "AddNewTables", "Add New Tables" },
		{ "AddPKey", "Add Primary Key" },
		{ "AddRow", "Add Row" },
		{ "AddRowDetailRowNo", "Auto Detail No" },
		{ "AddSKey", "Add Secondary Key" },
		{ "AddTabDialogComment", "* A 'tab' for another detail table will be added." },
		{ "AddTabDialogKeyComment", "* Specify DTL Table Keys according to HDR Table Keys. Initial value is the primary key of the DTL Table." },
		{ "AddTabDialogTitle", "Add Detail Tab" },
		{ "Alias", "Alias" },
		{ "Alignment", "Alignment" },
		{ "AllSubsystems", "(All Subsystems)" },
		{ "AndSoOn1", ""," and other " },
		{ "AndSoOn2", " elements." },
		{ "AppendCheckDeleteError1", "Deleting not allowed as this record is joined by " },
		{ "AppendCheckDeleteError2", "" },
		{ "AppendCheckDeleteMessage", "Append delete-check based on join definitions to this table?" },
		{ "AppendCheckDeleteTitle", "Appending Check Delete" },
		{ "AppendCheckDeleteWarning", "It contains error step(s). Check and edit them." },
		{ "Application", "Application" },
		{ "AppServerName", "DB-Method URL" },
		{ "AskIfReplacing", "Specified file is existing. You may replace it?" },
		{ "AssistListMessage", "No element found as a candidate." },
		{ "AttributeName", "Attribute" },
		{ "AttributeType", "Attribute Type" },
		{ "AttributeValue", "Value" },
		{ "AutoConnect", "Get DB-Connection to edit" },
		{ "AutoNumberID", "Auto-No" },
		{ "AutoRowNumber", "Auto Row Number" },
		{ "AvailableConnection", "DB Connection" },
		{ "BackToEdit", "Back to Editting" },
		{ "BackupFile", "Backup File" },
		{ "BackupFileMessage", "Do you backup current file before saving?" },
		{ "BarcodeType", "Barcode Type" },
		{ "BatchField", "Batch Field" },
		{ "BatchKey", "Batch Key" },
		{ "BatchKeyAbout", "*Those records with identical values of 'batch key' field(s) are counted as a 'batch'. Records of the batch table will be inserted one by one batch. Specify batch key of the primary table with datasource name and without for the batch table. Use ';' to separate fields." },
		{ "BatchKeyField", "Key Field of Batch Processing" },
		{ "BatchRecordCallID", "Batch Function" },
		{ "BatchRecordCallMsg", "Check To Run" },
		{ "BatchTable", "Batch Table" },
		{ "BatchTableDialogTitle", "Edit Batch Table Config" },
		{ "BatchWithKeyField", "With-Key Field to Batch Table" },
		{ "Bookmark", "Add/Remove Bookmarks" },
		{ "Both", "Both" },
		{ "Bracket1", "[" },
		{ "Bracket2", "]" },
		{ "BrowseHelp", "X-TEA Help" },
		{ "Button", "Function Key" },
		{ "ButtonPositionComment", "0(Left End) - 6(Right End)" },
		{ "ButtonPositionComment0_5", "0(Left End) - 5(Right End)" },
		{ "ByteaType", "File Type Field" },
		{ "CallFunction", "Calling" },
		{ "CallModeler", "Call Modeler" },
		{ "CallPromptFunction", "Call ID" },
		{ "Cancel", "Cancel" },
		{ "CancelChanges", "Cancel changes" },
		{ "Caption", "Caption" },
		{ "CaptionErrorMessage", "Caption value contained invalid character '(' or ')' or ','.\nThey were removed from the value." },
		{ "CaptionLengthVariable", "Width Auto-Adjusted" },
		{ "CaseSensitive", "Case Sensitive" },
		{ "Changed", "Changed" },
		{ "ChangeLabel", "ID / Name" },
		{ "CheckAllItems", "All Items"},
		{ "CheckAllModules", "Create All Table Modules"},
		{ "CheckAllModulesMessage1", "There is no table modules to be created."},
		{ "CheckAllModulesMessage2", "Those table modules to be created will be done at once."},
		{ "CheckContinueAdding", "Continue Adding"},
		{ "CheckFunctionsCalled", "Check Functions Called"},
		{ "CheckFunctionsCalledMessage1", "No errors found in relations of functions called."},
		{ "CheckFunctionsCalledMessage2", "The function is not called by any elements."},
		{ "CheckFunctionsCalledMessage3", "Function ID '"},
		{ "CheckFunctionsCalledMessage4", "' reffered in the script is not defined as a function in the system."},
		{ "CheckFunctionsCalledMessage5", "Function calling with ID'"},
		{ "CheckFunctionsCalledMessage6", "' is not defined as a function in the system."},
		{ "CheckFunctionsCalledMessage7", "Script '"},
		{ "CheckFunctionsCalledMessage8", "' contains function ID '"},
		{ "CheckFunctionsCalledMessage9", "' which is not defined as a function in the system."},
		{ "CheckFunctionsCalledMessage10", "Detail function is not specified whereas it's called by button to add."},
		{ "CheckFunctionsCalledMessage11", "Header function is not specified whereas it's called by button to process the header record."},
		{ "CheckFunctionsCalledMessage12", "ID of cross-checker to be pre-loaded is invalid."},
		{ "CheckFunctionsCalledMessage13", "ID of function to be pre-loaded is invalid."},
		{ "CheckLayout", "Check Layout"},
		{ "CheckLayoutTitle", "Check Panel Layout"},
		{ "CheckMark", "v"},
		{ "CheckUpdateOnly", "Update Only"},
		{ "ChooseAction", "File to be processed is not specified. If you want to create a new content file, \ncopy and rename 'Skeleton.xeaf' and specify it as the file to edit." },
		{ "ChooseXeadFile", "Choose model definition file(*.xead) imported from." },
		{ "ChooseXeafFile", "Choose system definition file(*.xeaf) imported from." },
		{ "ChooseXeafFileToDiff", "Choose system definition file(*.xeaf) to compare with." },
		{ "ClearValues", "Clear Val" },
		{ "Close", "Close" },
		{ "CloseNotSaving", "Discard" },
		{ "CloseSaving", "Save and Close" },
		{ "ColumnOnList", "Lists Including" },
		{ "Column", "Column" },
		{ "Columns", "Columns" },
		{ "Comma", ", " },
		{ "Comment", "Comment" },
		{ "Commit", "Commit" },
		{ "CommitCheck", "Check Commit" },
		{ "CommitCheckMessage", "Editting data is not completed. Execute commiting?" },
		{ "Compress", "Compress" },
		{ "Connection", "DB Connection" },
		{ "ConsoleOption", "Console" },
		{ "ConsoleOptionYes", "Show" },
		{ "ConsoleOptionTimer", "Timer" },
		{ "ControlOptions", "Control Options" },
		{ "CopiedNameExt", "(Copy)" },
		{ "Copy", "Copy" },
		{ "CopyToClipboard", "Copy to Clipboard" },
		{ "CreateDefinition", "Create" },
		{ "CreateInSubsystem", "In Subsystem" },
		{ "CreateTableComment", "* You can create table definitions one by one using SQL statement of CREATE TABLE. Only 'definitions' are created in this dialog. You need to create 'modules' afterward with definitions. Note that constraints of foreign keys are ignored and valid data types are those: CHAR,VARCHAR,TEXT,INTEGER,SMALLINT,BIGINT,DOUBLE,DECIMAL,NUMERIC,REAL,DATE,TIME,TIMETZ,TIMESTAMP,TIMESTAMPTZ" },
		{ "CreateTableDef", "Create Table Definitions" },
		{ "CreateTableStatement", "CREATE TABLE Statement" },
		{ "CreateTableTitle", "Create Table Definition by DDL" },
		{ "Data", "Data" },
		{ "Database", "Database" },
		{ "DatabaseMain", "Main DB" },
		{ "DatabaseSub", "Sub DB" },
		{ "DatabaseSubReadOnly", "Sub DB (read only)" },
		{ "DataMessages", "Specify 'Where' and 'OrderBy' criteria as neccessary." },
		{ "DataName", "Data Name" },
		{ "DataOutput", "Into EXCEL" },
		{ "DataSource", "Data Source" },
		{ "DataType", "Data Type" },
		{ "DataUtilityMessage1", "Input values and push 'Commit' button." },
		{ "DataUtilityMessage2", "The record has been updated successfully." },
		{ "DataUtilityMessage3", "Error: Another user has update this record\nbefore you have read and tried to update." },
		{ "DataUtilityMessage4", "Error: Inserting failed because of the unique key duplication." },
		{ "DataUtilityMessage5", "The record has been inserted successfully." },
		{ "DataUtilityMessage6", "The record has been deleted successfully." },
		{ "DataUtilityMessage7", "The table has been compressed successfully." },
		{ "DataUtilityMessage8", "This operation is not permitted for this table." },
		{ "DateFormat", "Date Format" },
		{ "DBConnect", "Connect DB" },
		{ "DBConnectMessage0", "X-TEA Editor - Check Database Service" },
		{ "DBConnectMessage1", "It failed to connect to the database '" },
		{ "DBConnectMessage2", "'.\nCheck if the database service has been started.　You can try to connect later using Tool menu." },
		{ "DBConnectMessage3", "Retry " },
		{ "DBConnectMessage4", "Skip connecting" },
		{ "DBConnectMessage5", "DB connection will be established. And also modules-check will\n be done for all table definitions. All right to execute?" },
		{ "DBConnectMessage6", "Connecting" },
		{ "DBConnectMessage7", "Error in detail" },
		{ "DBConnectMessage8", "DB Connection is ready." },
		{ "DBConnectMessage9", "Accessing to DB failed. Retry connectiong using Tool Menu." },
		{ "DBCPOptions", "DBCP Options" },
		{ "Decimal", "Decimal" },
		{ "DefaultFunctionNameXF000", "Script" },
		{ "DefaultFunctionNameXF100A", "Work with " },
		{ "DefaultFunctionNameXF100B", "" },
		{ "DefaultFunctionNameXF110A", "List update of " },
		{ "DefaultFunctionNameXF110B", "" },
		{ "DefaultFunctionNameXF200A", "Single update of " },
		{ "DefaultFunctionNameXF200B", "" },
		{ "DefaultFunctionNameXF290A", "Single print of " },
		{ "DefaultFunctionNameXF290B", "" },
		{ "DefaultFunctionNameXF300A", "Work with " },
		{ "DefaultFunctionNameXF300B", " and related list" },
		{ "DefaultFunctionNameXF310A", "Update " },
		{ "DefaultFunctionNameXF310B", " and related list" },
		{ "DefaultFunctionNameXF390A", "Print " },
		{ "DefaultFunctionNameXF390B", " and related list" },
		{ "Delete", "Delete" },
		{ "DeleteCanceled", "Delete canceled." },
		{ "DeleteCheckMessage", "Ok to delete this row?" },
		{ "DeleteCheckTitle", "Check Delete" },
		{ "DeleteDefinitionAndModule", "Delete definition and module" },
		{ "DeleteDefinitionOnly", "Delete definition only" },
		{ "DeleteFunction", "Deleting a function" },
		{ "DeleteTableMessage", "Deleting the table module as well as its definition?\nNote that records will be cleared if module is deleted." },
		{ "DeleteTableModule", "Deleting Table Module" },
		{ "Descent", "(Descent)" },
		{ "Descriptions", "Descriptions" },
		{ "Detail", "Detail Tab" },
		{ "DetailFunction", "Detail Function" },
		{ "DetailRowNumber", "Process last key field as row number" },
		{ "DetailRowNumberAuto", "Auto-Row-Numbering" },
		{ "DetailTable", "Detail Table" },
		{ "DriverVMOptions", "VM Opt." },
		{ "DTLField", "Column" },
		{ "DTLFields", "Columns" },
		{ "DTLFont", "DTL Font" },
		{ "DTLFunction", "DTL Function" },
		{ "DTLFunctionID", "DTL Function ID" },
		{ "DTLTable", "DTL Table" },
		{ "DTLTableID", "DTL Table ID" },
		{ "DTLTableKeys", "DTL Table Keys" },
		{ "DTLTabs", "DTL Tabs" },
		{ "Edit", "Edit" },
		{ "Editable", "Editable" },
		{ "EditableOptions", "Edit Option" },
		{ "EditCode", "Edit Code" },
		{ "EditDetailTableKeyTitle", "Edit DTL Table and Key" },
		{ "EditDetailTableKeyComment", "Specify unique keys of the header table and the detail table. Upper common fields must be as the same data type. All fields of PK(or SK) are required for DTL table key." },
		{ "EditKeyFieldsToPutIntoKey", "Put into Key"},
		{ "EditKeyFieldsToRemoveFromKey", "Remove from key"},
		{ "EditKeyFieldsToGoUp", "Go Up"},
		{ "EditKeyFieldsToGoDown", "Go Down"},
		{ "EditKeyFieldsToSetAscDesc", "Change A/D"},
		{ "EditKeyFieldsToRemove", "Remove"},
		{ "EditMode", "Edit Mode" },
		{ "EditOrderByMessage", "Specify DataSource names with ';' to separate them.\nBy putting '(D)' after names"," it will work as DESCENT order field." },
		{ "EditorUser", "Editor User" },
		{ "EditReferWithKeyMessage", "Specify ID(s) of fields with its table ID according to the key configuration \nof the join-table. Use ';' to separate them." },
		{ "EditDetailTableKeyTitle", "Edit Table and Key" },
		{ "EditTableKeyTitle", "Edit Table and Key" },
		{ "EditTableScript", "Open large editor" },
		{ "EditTableScriptTitle", "Edit Table Script" },
		{ "EditTypeNormal", "Normal Edit" },
		{ "EditTypeNoEdit", "No Edit" },
		{ "EditTypeZeroSuppress", "Zero Suppress" },
		{ "EditTypeHourMinuite", "Time(HH:MM)" },
		{ "ElementName", "Name" },
		{ "ElementType", "Element" },
		{ "ElementStatus", "Status" },
		{ "EOL", "End of line" },
		{ "ErrorLog1", "Error Log named " },
		{ "ErrorLog2", " was generated." },
		{ "ErrorMessage1", "Error occured at [" },
		{ "ErrorMessage2", "]. Close X-TEA Editor\nand refer to error log(xeadedt_err_....txt)" },
		{ "ErrorMessage3", "Field not found with ID'" },
		{ "ErrorMessage4", "'." },
		{ "ErrorMessage5", "Error: This is not a INTEGER field." },
		{ "ErrorMessage6", "Error: The first field is invalid." },
		{ "ErrorMessage7", "Error: The second field is invalid." },
		{ "ErrorMessage8", "Error: These are the same field." },
		{ "ErrorMessage9", "Error: Specify fields of the same type and length." },
		{ "ErrorMessage10", "Error: The first field must be part of the primary key." },
		{ "ErrorMessage11", "Field '" },
		{ "ErrorMessage12", "' is not valid or does not exist." },
		{ "ErrorMessage13", "Value specified is out of the range(" },
		{ "ErrorMessage14", ")." },
		{ "ErrorMessage15", "Error: Value specified is not a number" },
		{ "ErrorMessage16", "Error: Definition with ID '" },
		{ "ErrorMessage17", "' already exists." },
		{ "ErrorMessage18", "Error: Table definition with ID '" },
		{ "ErrorMessage19", "'\nalready exist under this or the other subsystem." },
		{ "ErrorMessage20", "Error: Deleting rejected as this subsystem has tables or functions." },
		{ "ErrorMessage21", "Error: Deleting rejected as tables or functions using this table exist." },
		{ "ErrorMessage22", "Error: This function is already on the menu." },
		{ "ErrorMessage23", "Error: No more room for another menu option." },
		{ "ErrorMessage24", "Margin values are invalid. They were reset as default(50;50;50;50)." },
		{ "ErrorMessage25", "Error: Command [" },
		{ "ErrorMessage26", "] failed.\n" },
		{ "ErrorMessage27", "Browsing Help failed." },
		{ "ErrorMessage28", "Saving file failed." },
		{ "ErrorMessage29", "Error: Deleting rejected as functions using this font exist." },
		{ "ErrorMessage30", "Error: Deleting rejected as least one element is required." },
		{ "ErrorMessage31", "Error: Deleting rejected as functions or join-tables reffering to this element exist." },
		{ "ErrorMessage32", "Error: Deleteing rejected as " },
		{ "ErrorMessage33", " fields are checked and used as refer fields.\nPut mouse cursor on them to check usage in the system." },
		{ "ErrorMessage34", "This function is used by other elements. Sure to delete?" },
		{ "ErrorMessage35", "X-TEA Modeler content file can not be processed with the name of " },
		{ "ErrorMessage36", "Error: Deleting rejected as this function is used in menu '" },
		{ "ErrorMessage37", "'" },
		{ "ErrorMessage38", "Error: It will lose consistency with new order of join tables.\nAll with-key values of each join table must be gained by preceding joins." },
		{ "ErrorMessage39", "Editting key definition is not allowed as\nfunctions or tables using this table exist." },
		{ "ErrorMessage40", "Error: Alias is needless for batch key field of the batch table." },
		{ "ErrorMessage41", "Error: Batch key(s) of the primary table is invalid. " },
		{ "ErrorMessage42", "Error: Batch key(s) of the batch table is invalid. " },
		{ "ErrorMessage43", "Error: Data type and size of coresponging fields of batch key must be the same. " },
		{ "ErrorMessage44", "Error: Alias is required for batch key field of the primary table. " },
		{ "ErrorMessage45", "Error: Numbers of fields are not matched between the primary table and the batch table. " },
		{ "ErrorMessage46", "Error: Alias is needless for 'With-Key Field'." },
		{ "ErrorMessage47", "Error: Field ID of 'With-Key Field' is invalid." },
		{ "ErrorMessage48", "Error: Field ID of 'With-Key for List' is invalid." },
		{ "ErrorMessage49", "Error: Data type and size of coresponging fields must be the same." },
		{ "ErrorMessage50", "Error: Field ID of 'With-Key for List' must be of a field or a join field of the header table." },
		{ "ErrorMessage51", "Error: Field ID of 'With-Key for List' must be with its alias." },
		{ "ErrorMessage52", "Error: Numbers of fields are not matched between those keys." },
		{ "ErrorMessage53", "Error: 'Return-From Field' is invalid." },
		{ "ErrorMessage54", "Error: 'Return-To Field' is invalid." },
		{ "ErrorMessage55", "Error: Data type and size of coresponging fields must be the same." },
		{ "ErrorMessage56", "Error: IDs of 'Return-To Field' must be with its alias." },
		{ "ErrorMessage57", "Error: IDs of 'Return-From Field' must be with its alias." },
		{ "ErrorMessage58", "Error: Numbers of fields are not matched between those keys." },
		{ "ErrorMessage59", "Error: Data Source of Fields-Putting '" },
		{ "ErrorMessage60", "' is invalid." },
		{ "ErrorMessage61", "Error: IDs of Fields-Putting must be with its alias." },
		//{ "ErrorMessage62", "Error: Data Source of Fields-Putting-To '" },
		//{ "ErrorMessage63", "' is invalid." },
		{ "ErrorMessage64", "Error: IDs of Fields-Putting-To must be with its alias." },
		{ "ErrorMessage65", "Error: Numbers of fields of Fields-Putting and Fields-Putting-To unmatch." },
		{ "ErrorMessage66", "Error: Numbers of fields of Fields-Getting and Fields-Getting-To unmatch." },
		//{ "ErrorMessage67", "Error: Data Source of Fields-Getting '" },
		//{ "ErrorMessage68", "' is invalid." },
		{ "ErrorMessage69", "Error: IDs of Fields-Getting must be with its alias." },
		{ "ErrorMessage70", "Error: Data Source of Fields-Getting-To '" },
		{ "ErrorMessage71", "' is invalid." },
		{ "ErrorMessage72", "Error: IDs of Fields-Getting-To must be with its alias." },
		{ "ErrorMessage73", "Error: Specify keys to process DTL records." },
		{ "ErrorMessage74", "Error: Number of DTL Table Keys must be more than HDR Table Keys." },
		{ "ErrorMessage75", "Error: Field ID '" },
		{ "ErrorMessage76", "' is invalid." },
		{ "ErrorMessage77", "Error: Data type and size of DTL table key field coresponging to HDR table key field must be the same." },
		{ "ErrorMessage78", "Error: Specify function ID." },
		{ "ErrorMessage79", "Error: Specify function type." },
		{ "ErrorMessage80", "Error: Specify function name." },
		{ "ErrorMessage81", "Error: The function with this ID already exists\nin this or another subsystem." },
		{ "ErrorMessage82", "Generating definition failed as the table specified is lacking primary key." },
		{ "ErrorMessage83", "Generating definition failed as the primary table specified is lacking primary key." },
		{ "ErrorMessage84", "Generating definition failed as the DTL table specified is lacking primary key." },
		{ "ErrorMessage85", "Error: Specify keys of HDR/DTL tables." },
		{ "ErrorMessage86", "Error: Specify physical fields on the primary table with ';' to separate them." },
		{ "ErrorMessage87", "Error: Field ID is invalid." },
		{ "ErrorMessage88", "Error: Specify physical fields on the HEADER table with ';' to separate them." },
		{ "ErrorMessage89", "Error: Specify physical fields on the DTL table with ';' to separate them." },
		{ "ErrorMessage90", "Error: Table ID is invalid." },
		{ "ErrorMessage91", "Error: This table is already joined. You can avoid\nduplication by specifying alias for this table." },
		{ "ErrorMessage92", "Error: Specify join-to/with keys." },
		{ "ErrorMessage93", "Error: Number of key fields are different." },
		{ "ErrorMessage94", "Error: Data type or size of corresponging key field is different." },
		{ "ErrorMessage95", "The first digit must be a single byte alphabet." },
		{ "ErrorMessage96", "Use single byte alpha-numeric characters." },
		{ "ErrorMessage97", "Error: Creating the table definition failed as the statement is invalid." },
		{ "ErrorMessage98", "The definition of table '" },
		{ "ErrorMessage99", "' has been created successfully." },
		{ "ErrorMessage100", "Error: Creating the table definition failed as table '" },
		{ "ErrorMessage101", "' already exists in this or another subsystem." },
		{ "ErrorMessage102", "Error: The field '" },
		{ "ErrorMessage103", "' has invalid data type(" },
		{ "ErrorMessage104", "). This field was eliminated from the table definition." },
		{ "ErrorMessage105", "Error: Character '_' is not allowed for the value." },
		{ "ErrorMessage106", "Error: Specify keys to process HDR records." },
		{ "ErrorMessage107", "Error: Deleting rejected as tables targetting to this database exist." },
		{ "ErrorMessage108", "Data-source-name specified is invalid." },
		{ "ErrorMessage109", "No need to include tableID in fieldID." },
		{ "ErrorMessage110", "Field ID of 'Upper Keys' in invalid." },
		{ "ErrorMessage111", "'Upper Keys' and PK of the header table is not corresponding about its data type." },
		{ "ErrorMessage112", "Field ID of 'Child Keys' in invalid." },
		{ "ErrorMessage113", "'Child Keys' and PK of the header table is not corresponding." },
		{ "ErrorMessage114", "Size of structure view is invalid. Value is set as default." },
		{ "ErrorMessage115", "Field ID must be a single value." },
		{ "ErrorMessage116", "Field value list or icon list is invalid." },
		{ "ErrorMessage117", "Field ID of order-by field is invalid." },
		{ "ErrorMessage118", "Alias is invalid as it's one of existing table id." },
		{ "ErrorMessage119", "Those will be invalid data-source-name if you change table ID.\n" },
		{ "ErrorMessage120", "Remove them from the function definition and retry changing." },
		{ "ErrorMessage121", "Field ID specified is invalid." },
		{ "ErrorMessage122", "Config of 'Node Text' will be invalid with this change." },
		{ "ErrorMessage123", "This change is not permitted as 'Structure table' is specified." },
		{ "ErrorMessage124", "Changing PK is not permitted as the table module exists." },
		{ "ErrorMessage125", "Deleting is not allowed as this join-table is used\nas 'Execute When' of the table-script as follows." },
		{ "ErrorMessage126", "Function ID specified is invalid." },
		{ "ErrorMessage127", "Size of ID is too long." },
		{ "ErrorMessage128", "Note that you can not edit in 'NAME-mode'." },
		{ "ErrorMessage129", "It failed to save backup." },
		{ "ErrorMessage130", "As number of tabs are in maximum, adding tab not allowed." },
		{ "ErrorMessage131", "ID with space is ignored." },
		{ "EventAC", "AfterC" },
		{ "EventAD", "AfterD" },
		{ "EventAR", "AfterR" },
		{ "EventAU", "AfterU" },
		{ "EventBC", "BeforeC" },
		{ "EventBD", "BeforeD" },
		{ "EventBR", "BeforeR" },
		{ "EventBU", "BeforeU" },
		{ "EventReferAR", "After Reading All Join Tables" },
		{ "EventReferAR1", "After Reading Table '" },
		{ "EventReferAR2", "'" },
		{ "EventReferAS", "After Processing detail records" },
		{ "EventReferBR", "Before Reading All Join Tables" },
		{ "EventReferBR1", "Before Reading Table '" },
		{ "EventReferBR2", "'" },
		{ "ExchangeParms", "Parm." },
		{ "ExchangeFields", "Field to be exchanged to prompt" },
		{ "Execute", "Execute" },
		{ "ExecuteWhen", "Execute When" },
		{ "ExecuteWhenJoin", "Execute When (Join Table)" },
		{ "Exit", "Exit" },
		{ "ExitMessage", "Save changes to exit?" },
		{ "ExitNotSaving", "Discard" },
		{ "ExitSaving", "Save and Exit" },
		{ "ExtentionInvalid", "Extention of the file is invalid." },
		{ "F3ToScan", "F3:Scan" },
		{ "FailedToParse", "It failed to parse xead file specified. Check format of file." },
		{ "Field", "Field" },
		{ "FieldAccountDate", "Acc.Date" },
		{ "FieldBoolean", "Boolean" },
		{ "FieldColumnName", "Column Name" },
		{ "FieldColumnName2", "Col. Name" },
		{ "FieldDialNo", "Phone" },
		{ "FieldExtType", "Ext-Type" },
		{ "FieldFiscalYear", "Fis.Year" },
		{ "FieldID", "Field ID" },
		{ "FieldImageFile", "Image File" },
		{ "FieldKana", "Kana" },
		{ "FieldKanji", "Kanji" },
		{ "FieldKubunID", "U.Def-Code" },
		{ "FieldMargin", "Margin" },
		{ "FieldMonthSeq", "Fis.Month" },
		{ "FieldName", "Field Name" },
		{ "FieldOptions", "settings" },
		{ "FieldRows", "Rows" },
		{ "Fields", "Fields" },
		{ "FieldSize", "Size" },
		{ "FieldsToExchangeComment", "* Specify field IDs to exchange with the prompt function. Use ';' to separate IDs." },
		{ "FieldsToExchangeDialog", "Fields to Exchange with Prompt Function" },
		{ "FieldsToGet", "Fields Getting" },
		{ "FieldsToGetTo", "Fields Getting to" },
		{ "FieldsToPut", "Fields Putting" },
		{ "FieldsToPutTo", "Fields Putting to" },
		{ "FieldType", "Data Type" },
		{ "FieldURL", "URL" },
		{ "FieldUsageInScript1", "Variant Field in Script '" },
		{ "FieldUsageInScript2", "'" },
		{ "FieldUsageInScript3", "Variant Field in Script" },
		{ "FieldUsageMessage1", "Usage of " },
		{ "FieldUsageMessage2", "" },
		{ "FieldUsageToKeyField", "To-Key Field of Join Table" },
		{ "FieldUsageWithKeyField1", "With-Key Field to Join Table(" },
		{ "FieldUsageWithKeyField2", ")" },
		{ "FieldValueList", "Value List" },
		{ "FieldWidth", "Width" },
		{ "FieldYearMonth", "YearMonth" },
		{ "FieldZipNo", "ZIP No" },
		{ "FieldZipAdrs", "Link Add." },
		{ "File", "File" },
		{ "FileDiff", "List Diff of Files" },
		{ "FileDiffMessage", "Differences between the current file and the target file will be listed. Push button to start."},
		{ "FileDiffMessage01", " changed"},
		{ "FileDiffMessage02", "'s "},
		{ "FileDiffMessage03", " changed from '"},
		{ "FileDiffMessage04", "' to '"},
		{ "FileDiffMessage05", "'"},
		{ "FileDiffMessage06", " '"},
		{ "FileDiffMessage07", "'"},
		{ "FileDiffMessage08", " added"},
		{ "FileDiffMessage09", " deleted"},
		{ "FileDiffMessage10", " changes has been found."},
		{ "FileDiffMessage11", "'s columns changed"},
		{ "FileDiffMessage12", "'s filters changed"},
		{ "FileDiffMessage13", "'s buttons changed"},
		{ "FileDiffNone", "No Changes"},
		{ "FileDiffTargetFile", "Target File"},
		{ "FileDiffTargetSystem", "Target System"},
		{ "FileDiffTitle", "List Diff of Files" },
		{ "FileNameImporting", "File Importing From" },
		{ "FileSpecifiedNotFound", "File with specified name and the valid extention is not found." },
		{ "FileUpdateMessage", "This file has been already updated by the other user. Save changes?" },
		{ "FilterOfDetailList", "Filter of Detail List" },
		{ "FilterOption", "Filter Option" },
		{ "Filter", "Filter" },
		{ "Filters", "Filters" },
		{ "FixedWhere", "Fixed Where" },
		{ "FixedWhereDTL", "DTL Fixed Where" },
		{ "FixedWhereHDR", "HDR Fixed Where" },
		{ "Font", "Font" },
		{ "FontSize", "Size" },
		{ "FontStyle", "Style" },
		{ "FontStyleBold", "Bold" },
		{ "FontStyleBoldItalic", "BoldItalic" },
		{ "FontStyleItalic", "Italic" },
		{ "FontStyleNormal", "Normal" },
		{ "FontStyleUnderlined", "Underlined" },
		{ "FormatVersionError1", "Format Version of this X-TEA Editor content file is " },
		{ "FormatVersionError2", ". Format Version this application can handle with is upto " },
		{ "FormatVersionError3", ". Please use the latest program." },
		{ "FunctionDefinition", "Function" },
		{ "FunctionDefinitions", "Functions" },
		{ "FunctionID", "Function ID" },
		{ "FunctionKeyNo", "Function Key No" },
		{ "FunctionKeys", "Function Keys" },
		{ "FunctionList", "Function List" },
		{ "FunctionName", "Function Name" },
		{ "FunctionsWhereUsed", "Where-Used" },
		{ "FunctionType", "Function Type" },
		{ "FunctionTypeXF000", "XF000 Script Launcher" },
		{ "FunctionTypeXF010", "XF010 Script Launcher #1" },
		{ "FunctionTypeXF100", "XF100 Inquiry List" },
		{ "FunctionTypeXF110", "XF110 Update List" },
		{ "FunctionTypeXF200", "XF200 Single CRUD" },
		{ "FunctionTypeXF210", "XF210 Single Update" },
		{ "FunctionTypeXF290", "XF290 Single Print" },
		{ "FunctionTypeXF300", "XF300 HDR/DTL Inquiry" },
		{ "FunctionTypeXF310", "XF310 HDR/DTL Update" },
		{ "FunctionTypeXF390", "XF390 HDR/DTL Print" },
		{ "Function/AddRowListButton", "Function / Add-Row-List Button" },
		{ "Function/AddRowListField", "Function / Add-Row-List Field" },
		{ "Function/BatchField", "Function / Batch Field" },
		{ "Function/Button", "Function / Button" },
		{ "Function/DTLButton", "Function / DTL Button" },
		{ "Function/DTLField", "Function / DTL Field" },
		{ "Function/DTLTab", "Function / DTL Tab" },
		{ "Function/Field", "Function / Field" },
		{ "Function/FieldTab", "Function / Field Tab" },
		{ "Function/Filter", "Function / Filter" },
		{ "Function/HDRField", "Function / HDR Field" },
		{ "Function/HDRPhrase", "Function / HDR Phrase" },
		{ "Function/Phrase", "Function / Phrase" },
		{ "GenerateList", "Output" },
		{ "HashFormat", "Hash Format" },
		{ "HashFormatMessage1", "*You can try hashing by the format. Specify original value and push the button." },
		{ "HashFormatMessage2", "*The format is invalid. It has to contain algorithm, count of expansion and whether to be salted or not. Those element are separated by semicolon." },
		{ "HashFormatSalt", "Salt Value" },
		{ "HashFormatTitle", "Checking Hash Format" },
		{ "HashFormatValue", "Original Value" },
		{ "HDRData", "HDR Data" },
		{ "HDRField", "HDR Area Field" },
		{ "HDRFields", "HDR Fields" },
		{ "HDRFunctionID", "HDR Func.ID" },
		{ "HDRTable", "HDR Table" },
		{ "HDRTableKeys", "HDR Table Keys" },
		{ "HeaderFunction", "HDR processor" },
		{ "HeaderParmAdditional", "Additional parms for HDR processor" },
		{ "HeaderTable", "Header Table" },
		{ "Height", "Height" },
		{ "Help", "Help" },
		{ "Hidden", "Hidden" },
		{ "HitCount", "Hit" },
		{ "ID", "ID" },
		{ "IDAndName", "ID/Name" },
		{ "IDWithLength1", "ID(LE" },
		{ "IDWithLength2", "digits)" },
		{ "IgnoreIfZero", "Ignore If 0" },
		{ "ImageFolder", "Image Folder" },
		{ "Import", "Import" },
		{ "ImportData", "Import Tab-Separated-Value data" },
		{ "ImportDataMessage1", "Importing has completed with " },
		{ "ImportDataMessage2", " record(s) inserted and " },
		{ "ImportDataMessage3", " record(s) updated." },
		{ "ImportDataMessage4", "ERROR: Key field value is lacking." },
		{ "ImportDataMessage5", "ERROR: The first line of data contains duplicated field ID(or name)." },
		{ "ImportDataMessage6", " record(s) inserted." },
		{ "ImportDialogModelTitle", "Import From Model Definition File" },
		{ "ImportDialogTitle", "Import From System Definition File " },
		{ "ImportLayout", "Import" },
		{ "ImportMessage0", "Current file has been changed. Saving required to import." },
		{ "ImportMessage1", "* Press Import-button after checking any tables or functions to be imported. If ID of the element being imported is existing in another subsystem than the one to be imported into, process type of the element is shown as 'UNMATCH'. And if denifition of join-table is missing, it will be shown as 'NO_JOINNED'. Those elements will not be imported even if checked." },
		{ "ImportMessage2", "merged successfully."},
		{ "ImportMessage3", "replaced successfully."},
		{ "ImportMessage4", "added successfully."},
		{ "ImportMessage5", "importing skipped as irregularity containning. "},
		{ "ImportMessage6", "importing skipped as ID of the element existing in another subsystem than the one selected. "},
		{ "ImportMessage7", "Table definition joined to this table is missing in target system."},
		{ "ImportMessage8", "Join table key is invalid."},
		{ "ImportMessage9", "Join field is invalid."},
		{ "ImportMessage10", "Primary key is not allowed to alter."},
		{ "ImportMessage11", "Primary table is missing in target."},
		{ "ImportMessage12", "Primary table key is invalid."},
		{ "ImportMessage13", "Order-By of rows is invalid."},
		{ "ImportMessage14", "Detail field is invalid."},
		{ "ImportMessage15", "Filter field is invalid."},
		{ "ImportMessage16", "Batch table is missing in target."},
		{ "ImportMessage17", "Batch key is invalid."},
		{ "ImportMessage18", "Field is invalid."},
		{ "ImportMessage19", "Header table is missing in target."},
		{ "ImportMessage20", "Header table key is invalid."},
		{ "ImportMessage21", "Header field is invalid."},
		{ "ImportMessage22", "Detail table is missing in target."},
		{ "ImportMessage23", "Detail table key is invalid."},
		{ "ImportMessage24", "Detail field is invalid."},
		{ "ImportMessage25", "Add-Row-List table is missing in target."},
		{ "ImportMessage26", "Add-Row-List table key is invalid."},
		{ "ImportMessage27", "Order-By of Add-Row-List is invalid."},
		{ "ImportMessage28", "Exchange-List of Add-Row-List is invalid."},
		{ "ImportMessage29", "Add-Row-List field is invalid."},
		{ "ImportMessage30", "Function-Type is invalid."},
		{ "ImportMessage31", "Phrase Font is invalid."},
		{ "ImportMessage32", "Table Font is invalid."},
		{ "ImportMessage33", "Database is invalid."},
		{ "ImportMessage34", "Structure table is invalid."},
		{ "ImportMessage35", "Config of structure node text is invalid."},
		{ "ImportMessage36", "Control field of structure node icon is invalid."},
		{ "ImportModelMessage0", "*Choose the subsystem which contains elements to be imported. If chosen subsystem is not existing in the system imported into, the definition will be created automatically." },
		{ "ImportModelMessage1", "*Select the row of element and press 'Import' button. You can override ID of element then if neccessary." },
		{ "ImportModelMessage2", "Thie ID is already existing in either of current sybsystems. Importing is not allowed."},
		{ "ImportModelMessage3", "This definition does not exist in the current file. Press 'Import' to process this element."},
		{ "ImportModelMessage4", "Input ID if neccessary."},
		{ "ImportModelMessage5", "* Importing canceled as ID is blank."},
		{ "ImportModelMessage6", "Importing is not allowed as the primary-table is not specified."},
		{ "ImportModelMessage7", "Importing is not allowed as the primary-table is not yet defined in current system."},
		{ "ImportModelMessage8", "Importing is not allowed as the header-table is not specified."},
		{ "ImportModelMessage9", "Importing is not allowed as the header-table is not yet defined in current system."},
		{ "ImportModelMessage10", "Importing is not allowed as any valid detail-table is not specified."},
		{ "ImportModelMessage11", "Importing is not allowed as the detail-table is not yet defined in current system."},
		{ "ImportModelMessage12", "Importing is not allowed as its function type is not valid."},
		{ "ImportModelMessage13", "Importing is not allowed as data type of any field is not valid."},
		{ "ImportModelMessage14", "Importing is not allowed as ID of any field is blank."},
		{ "ImportModelMessage15", "Imported successfully."},
		{ "ImportModelMessage16", "Importing is not allowed as the header table key is not 'upper key' of detail table."},
		{ "ImportModelMessage17", "Importing is not allowed as ID of any field is duplicated in the table definition."},
		{ "ImportModelMessage18", "Definitions are different. Press 'Import' to process this element. Note that not all differences will be processed."},
		{ "ImportModelMessage19", "As definitions are identical, no need to be imported."},
		{ "ImportModelMessage20", "Importing is not allowed as the definition to be imported contains errors."},
		{ "ImportModelMessage21", "Name differs, current value is '"},
		{ "ImportModelMessage22", "'"},
		{ "ImportModelMessage23", "Subsystem differs, current value is '"},
		{ "ImportModelMessage24", "' "},
		{ "ImportModelMessage25", " is added."},
		{ "ImportModelMessage26", " is missing."},
		{ "ImportModelMessage27", " is defined."},
		{ "ImportModelMessage28", "Element type differs, current value is '"},
		{ "ImportModelMessage29", "<Errors>"},
		{ "ImportModelMessage30", "<Diff in File Importing From>"},
		{ "ImportSaveMessage", "Save what you have imported?" },
		{ "ImportSaveTitle", "X-TEA Editor - Save Import" },
		{ "ImportXEAD", "From X-TEA Modeler File(*.xead)" },
		{ "ImportXEAF", "From X-TEA Editor File(*.xeaf)" },
		{ "Index", "Index" },
		{ "InitialListing", "List when launched" },
		{ "InitialMessage", "Initial Message" },
		{ "InitialReadCount", "Scanning By" },
		{ "InitialValue", "Initial Value" },
		{ "InputAssistList", "Generic" },
		{ "InsertInitialRecordData1", "Log-in Permission Flag" },
		{ "InsertInitialRecordData2", "System Administrator" },
		{ "InsertInitialRecordData3", "General" },
		{ "InsertInitialRecordData4", "Regular" },
		{ "InsertInitialRecordData5", "Part-Time" },
		{ "InsertInitialRecordData6", "subject" },
		{ "InsertInitialRecordData7", "not' subject" },
		{ "JavaVersionError1", "Launching X-TEA Editor failed as Java version is " },
		{ "JavaVersionError2", ". Required version is 1.7 - 1.8." },
		{ "JoinField", "Join Field" },
		{ "JoinFields", "Join Fields" },
		{ "JoinRecordExist", "Record Exist" },
		{ "JoinRecordOptional", "Optional" },
		{ "JoinTable", "Join Table" },
		{ "JoinTables", "Join Tables" },
		{ "JoinTableWithAlias", "Join Table"," Alias=" },
		{ "JoinToKeys", "To Keys" },
		{ "JoinWithKeys", "With Keys" },
		{ "Jump", "Jump" },
		{ "JumpTo1", "Jump to \"" },
		{ "JumpTo2", "\"" },
		{ "JumpToBookmark", "Jump to bookmark" },
		{ "KeyFieldID", "Key Field ID" },
		{ "KeyFieldName", "Key Field Name" },
		{ "KeyFieldOfDTLTable", "Key Field of Detail Table" },
		{ "KeyFieldOfHDRTable", "Key Field of Header Table" },
		{ "KeyFieldOfPrimaryTable", "Key Field of Primary Table" },
		{ "KeyFields", "Key Fields" },
		{ "Key", "Key" },
		{ "Keys", "Keys" },
		{ "KeyType", "Key Type" },
		{ "KeywordList", "Keyword List" },
		{ "Launch", "Launch System" },
		{ "LaunchSystemTitle", "Save changes in current file before launching system?" },
		{ "LayoutHidden", "Hidden" },
		{ "LayoutHorizontal", "Horizontal" },
		{ "LayoutOption", "Layout Option" },
		{ "LayoutVertical", "Vertical" },
		{ "Lines", "lines" },
		{ "LinkedFunction", "Linked To" },
		{ "LinkedFunctionExchange", "Exchanged field of a linked function" },
		{ "List", "List" },
		{ "ListBox", "ListBox" },
		{ "ListItemMark", "- " },
		{ "ListCsv", "List CSV" },
		{ "ListingOperations", "Listing" },
		{ "ListLog", "List Log" },
		{ "ListLogComment", "* Only those table operations executed in sessions by X-TEA Driver are listed. And also operations with 'WHERE' criteria values are matching or partial to the key values of the specified record." },
		{ "ListLogMessage1", " log(s) found to be listed. Select the row to see details." },
		{ "ListLogMessage2", "No log found to be listed." },
		{ "ListLogTitle", "List Log of Table Operations" },
		{ "ListOrder", "Listing Order" },
		{ "ListTable", "List Table" },
		{ "LoginScript", "Login Script" },
		{ "LoginTime", "Login Time" },
		{ "MainDB", "Main DB" },
		{ "MainMenuEdit", "Edit(E)" },
		{ "MainMenuFile", "File(F)" },
		{ "MainMenuHelp", "Help(H)" },
		{ "MainMenuScan", "Scan(S)" },
		{ "MainMenuTools", "Tools(T)" },
		{ "Margin", "L/R Margin" },
		{ "Menu", "Menu" },
		{ "Menu/Option", "Menu / Option" },
		{ "MenuDefinition", "Menu Definition" },
		{ "MenuDefinitions", "Menus" },
		{ "MenuCrossCheckers", "X.Checkers preloaded" },
		{ "MenuFunctions", "Functions preloaded" },
		{ "MenuHelpURL", "Help URL" },
		{ "MenuID", "Menu ID" },
		{ "MenuIDAndName", "Menu ID/Name" },
		{ "MenuList", "Menu List" },
		{ "MenuName", "Menu Name" },
		{ "MenuOption", "Menu Option" },
		{ "MenuOptionName", "Menu Option Name" },
		{ "MenuOptions", "Menu Options" },
		{ "MenuTree", "Menu Tree" },
		{ "Message", "Message" },
		{ "MinusRejectMessage", "Minus expression is ignored." },
		{ "ModuleCheck", "Module Check" },
		{ "ModuleCheckMessage1", "Unmatched data-type or size of the field '" },
		{ "ModuleCheckMessage2", "'.\n. . . Its type on the definition is " },
		{ "ModuleCheckMessage3", ", whereas " },
		{ "ModuleCheckMessage4", " on the module.\n" },
		{ "ModuleCheckMessage5", "Field '" },
		{ "ModuleCheckMessage6", "' is nullable on the definition, whereas not-null on the module.\n" },
		{ "ModuleCheckMessage7", "Field '" },
		{ "ModuleCheckMessage8", "' is not-null on the definition, whereas nullable on the module.\n" },
		{ "ModuleCheckMessage9", "Field '" },
		{ "ModuleCheckMessage10", "' does not exis on the module.\n" },
		{ "ModuleCheckMessage11", "Update-counter field '" },
		{ "ModuleCheckMessage12", "' on the module is not INTEGER but " },
		{ "ModuleCheckMessage13", ".\n" },
		{ "ModuleCheckMessage14", "Update-counter field '" },
		{ "ModuleCheckMessage15", "' does not exist on the module.\n" },
		{ "ModuleCheckMessage16", "The physical field '" },
		{ "ModuleCheckMessage17", "' exists on the module but has no definition.\n" },
		{ "ModuleCheckMessage18", "Unique key '" },
		{ "ModuleCheckMessage19", "' exists on the module but has no definition.\n" },
		{ "ModuleCheckMessage20", "The index '" },
		{ "ModuleCheckMessage21", "' of the module does not exist on the defintion.\n" },
		{ "ModuleCheckMessage22", "The definitions of the primary key are different. Its '" },
		{ "ModuleCheckMessage23", "' on the definition, whereas '" },
		{ "ModuleCheckMessage24", "' on the module.\nNote that you have to delete and re-create the module to modify the primary key if it already exists.\n" },
		{ "ModuleCheckMessage25", "The secondary key '" },
		{ "ModuleCheckMessage26", "' does not exist on the module.\n" },
		{ "ModuleCheckMessage27", "The index '" },
		{ "ModuleCheckMessage28", "' does not exist on the module. Try modifying module.\n" },
		{ "ModuleCheckMessage29", "The primary key is not defined, whereas the module has one as '" },
		{ "ModuleCheckMessage30", "'. \n" },
		{ "ModuleCheckMessage31", "The table module does not exist." },
		{ "ModuleCheckMessage32", ". . . Complete definitions and create table module." },
		{ "ModuleCheckMessage33", ". . . You need to delete and re-create the module." },
		{ "ModuleCheckMessage34", ". . . Note that field(s) on the table module might be removed all with its data if you execute 'Modify Module' to modify field attributes. And also note that sometimes you have to try more than once to complete modifying module because of priority of attributes to be modified. If you want to remove a secondary uniqu key from tables, you need to use SQL console. Refer to HELP for details." },
		{ "ModuleCheckMessage35", "* The table module matches to the definition. No need to modify the module." },
		{ "ModuleCheckMessage36", "The table module will be modified according to\nthe current definition. Sure to execute?" },
		{ "ModuleCheckMessage37", "It failed to modify the table module.　Note that adding field should be nullable.\n\n" },
		{ "ModuleCheckMessage38", "Creating table module is not allowed as it contains no primary key." },
		{ "ModuleCheckMessage39", "The table module will be created according to the definition.\nNote that you have to delete the module to modify the primary key.\nSure to create?" },
		{ "ModuleCheckMessage40", "It failed to create the table module.\n\n" },
		{ "ModuleCheckMessage41", "The table module will be\ndeleted. Sure to execute?" },
		{ "ModuleCheckMessage42", "It failed to delete the table module." },
		{ "ModuleCheckMessage43", "* The table module has been created successfully." },
		{ "ModuleCheckMessage44", "* The table module is now sychronized to the definition. Modify table data if required." },
		{ "ModuleCheckMessage45", "* The table module matches to the definition. No need to alter the module although it has foreign-key constraint(s) which is not required by X-TEA Driver." },
		{ "ModuleCheckMessage46", "Type or length of field(s) of the primary key is different." },
		{ "ModuleCheckMessage47", "Missing elements will be compensated in the table definition according to the current table module.\nNote that non-supported data type will be translated to be 'CHAR'." },
		{ "ModuleCheckMessage48", "'.\n. . . Its type on the definition is double-byte " },
		{ "ModuleCreate", "Create Module" },
		{ "ModuleDelete", "Delete Module" },
		{ "ModuleModify", "Modify Module" },
		{ "ModulePut", "Compensate" },
		{ "Name", "Name" },
		{ "NameDialogTitle", "X-TEA Editor - Specify folder and file name" },
		{ "NewScript", "New Script" },
		{ "NewTab", "New Tab" },
		{ "Next", "Next" },
		{ "No", "No" },
		{ "NoCaption", "No Caption" },
		{ "NoFieldsLeftToBeAdded", "No fields left to be added." },
		{ "None", "None" },
		{ "NonEditable", "Non Editable" },
		{ "NoUpdate", "No Update" },
		{ "NumberFormatError", "Decimal point is invalid." },
		{ "Nullable", "Nullable" },
		{ "NullCheckMessage", "Null is not allowed." },
		{ "Open", "Open" },
		{ "OpenBrowsedFiles", "Recent Browsed Files" },
		{ "OpenExistintContent", "Open existing content file" },
		{ "OpenMessage", "Current file has been changed. Save changes to open file?" },
		{ "OpenNotSaving", "Open without Saving" },
		{ "OpenSaving", "Save and Open" },
		{ "OpenXEAFFile", "Open existing xeaf file." },
		{ "OptionalList", "Type-1" },
		{ "OptionName", "Option Name" },
		{ "Order", "List Order" },
		{ "OrderByFields", "Order By" },
		{ "OrderByOfDetailList", "Order-By Field of Detail List" },
		{ "Output", "Output" },
		{ "OutputFolder", "Output Folder" },
		{ "OverrideID", "Check to change ID" },
		{ "PageDirection", "Page Direction" },
		{ "PageMargins", "Margins(L;R;T;B)" },
		{ "PageNo", "With Page No" },
		{ "PageSize", "Page Size" },
		{ "PanelSize", "Panel Size" },
		{ "Parameters", "Exchanging" },
		{ "ParmAdditional", "Additional parms for row processor" },
		{ "Password", "Password" },
		{ "Paste", "Paste" },
		{ "PasteChild", "Paste child-node" },
		{ "PasteFromClipboard", "Paste" },
		{ "PasteToClipboard", "Copy" },
		{ "PhraseBlock", "Phrase Block" },
		{ "PhraseFormula", "Phrase Formula" },
		{ "PhraseSpacingAfter", "Spacing After" },
		{ "PhysicalField", "Physical Field" },
		{ "PKey", "Primary Key" },
		{ "Pos_short", "Pos." },
		{ "Position", "Position" },
		{ "Previous", "Previous" },
		{ "PrimaryTable", "Primary Table" },
		{ "PrintFont", "Print Font" },
		{ "ProcessRowIfOnlyOne", "Process row if only one listed" },
		{ "ProcessType", "Process" },
		{ "Prompt", "Prompt" },
		{ "PrompterFunction", "Function Prompter" },
		{ "PrompterFunctionExchange", "Exchanged field of a prompter" },
		{ "PrompterList", "List Prompter" },
		{ "ReadCheckMessage", " records are selected. Input next count to be selected." },
		{ "ReadCountMessage", " records are found with criteria specified." },
		{ "ReadEmptyMessage", "The table has no record." },
		{ "ReadNoneMessage", "No record found with criteria specified." },
		{ "ReadOnlyWarning1", "Specified is a Read-Only file. Note that you" },
		{ "ReadOnlyWarning2", "can not save what you have editted with X-TEA Editor." },
		{ "Redo", "Redo changes in node" },
		{ "Refer", "Join Table" },
		{ "Refresh", "Refresh" },
		{ "Remarks", "Remarks" },
		{ "RemoveRow", "Remove Row" },
		{ "ReplaceAll", "Replace all scanned" },
		{ "ReplaceAllSelected", "Replace all selected" },
		{ "ReplaceFile", "Replace" },
		{ "ReplaceSaveMessage", "Save what you have processed?" },
		{ "ReplaceSaveTitle", "X-TEA Editor - Save Replacing" },
		{ "ReplaceStringInScript", "To replace" },
		{ "RequiredList", "Type-2" },
		{ "Result", "Result" },
		{ "RetrieveLog", "Retrieve Log" },
		{ "Return", "Return" },
		{ "ReturnFields", "Return Fields" },
		{ "RowAction", "Row Action" },
		{ "RowActionCall", "Calling" },
		{ "RowActionReturn", "ReturnKey" },
		{ "RowNoWidth", "Row No Width" },
		{ "Save", "Save" },
		{ "SaveAs", "Save As" },
		{ "SaveAsThis", "Save As This Name" },
		{ "SaveChanges", "Save Changes" },
		{ "SaveChangesTitle", "X-TEA Editor - Saving Changes" },
		{ "Scan", "Scan" },
		{ "ScanDialogComment1", "Only those elements you can edit by X-TEA Editor are scanned. Elements like IDs and alias of join tables are not scanned as they are not edittable." },
		{ "ScanDialogComment2", " elements with " },
		{ "ScanDialogComment3", " of strings were found. Select any row to see detail value." },
		{ "ScanDialogComment4", "None of elements was found with the string." },
		{ "ScanDialogComment5", " elements with " },
		{ "ScanDialogComment6", " strings were replaced." },
		{ "ScanDialogTitle", "Scan/Replace String" },
		{ "ScanField", "Scan Field Definitions" },
		{ "ScanFieldFound", " of field definitions have been found." },
		{ "ScanFieldHintMessage", "* Specify strings with ';' to separate them. Use '*' for generics expression." },
		{ "ScanFieldNotFound", "No field definitions found by criteria specified." },
		{ "ScanMessage", "Current file has been changed. Saving required to scan." },
		{ "ScanRange", "Scanning" },
		{ "ScanReplace", "Scan/Replace String" },
		{ "ScanStart", "Scan" },
		{ "ScanString", "Scanning" },
		{ "ScanStringInScript", "Scan" },
		{ "ScanStringInScriptMessage1", "Not found." },
		{ "ScanStringInScriptMessage2", " string(s) replaced." },
		{ "ScanStringReplacedTo", "Replacing" },
		{ "Script", "Script" },
		{ "ScriptChangesMessage", "Save Changes in the script?" },
		{ "ScriptEditorFunctionKeys1", "F3=Scan/Replace String（from cursor） F7=Check Syntax" },
		{ "ScriptEditorFunctionKeys2", "Ctrl+I=Indent  Ctrl+N=NAME/ID  Ctrl+/=Comment" },
		{ "ScriptEditorFunctionKeys3", "Ctrl+Space=Code Assist  Ctrl+/=Comment F1=Help" },
		{ "ScriptError", "Script has a syntax error. Check row number." },
		{ "ScriptErrorNotFound", "No syntax error found." },
		{ "ScriptFontSize", "Change font size of scripts" },
		{ "ScriptFunctions", "Script Functions" },
		{ "ScriptHold", "Hold" },
		{ "ScriptNotesTitle1", "<< Native Field Variants List >>" },
		{ "ScriptNotesTitle2", "\n\n<< Join Field Variants List >>" },
		{ "ScriptNotesTitle3", "\n\n<< Legends of Variant Property >>\n[TableID]_[FieldID].value : Field value\n[TableID]_[FieldID].oldValue : Field value before update(read-only)\n[TableID]_[FieldID].valueChanged : Whether value has been changed or not(read-only:true,false)\n[TableID]_[FieldID].color : Font Color(black,green,blue,red,orange)\n[TableID]_[FieldID].enabled : Enabled(true,false)\n[TableID]_[FieldID].editable : Editable(true,false)\n[TableID]_[FieldID].valueList : Selectable Value List(array)\n[TableID]_[FieldID].error : Error message" },
		{ "ScriptNotesTitle4", "\n\n<< Functions Available >>\nYou can also use functions of 'session' and 'instance (of function)' \nas well as user-defined functions. Type Ctrl+Space \nfor candidates. Refer to the HELP for function usage in details." },
		{ "ScriptNotesVFMark", "(V/F) " },
		{ "Scripts", "Scripts" },
		{ "Search", "Next" },
		{ "Sel", "Sel" },
		{ "SelectAll", "All" },
		{ "SelectContent", "X-TEA Editor - Select Content File" },
		{ "SelectFile", "Select file and open" },
		{ "SelectFromList", "( Select from the list )" },
		{ "SelectList", "Select-List" },
		{ "ServiceName", "Service Name" },
		{ "SessionNo", "Session No" },
		{ "Size", "Size" },
		{ "SizeAuto", "Auto" },
		{ "SizeCheckMessage", "Length of the value is too long." },
		{ "SizeFull", "Full" },
		{ "SizeSpecified", "Specified(w,h)" },
		{ "SKey", "Secondary Key" },
		{ "SkipModuleCheck", "Skip module-checking to start Editor" },
		{ "SkipPreload", "Skip preloading to start Driver" },
//		{ "SmtpHost", "SMTP Host" },
//		{ "SmtpPort", "Port" },
//		{ "SmtpUser", "User ID" },
//		{ "SmtpPassword", "Password" },
		{ "SpecifyFunctionID", "Specify Function ID" },
		{ "SpecifyName", "Specify file name again" },
		{ "SpecifyNewID", "Specify ID of this element to add." },
		{ "SpecifyTableID", "Specify table ID." },
		{ "SplashMessage0", "Launching X-TEA Editor..." },
		{ "SplashMessage1", "Parsing System Definitions..." },
		{ "SplashMessage2", "Connecting to databases..." },
		{ "SplashMessage3", "Parsing Table Definitions..." },
		{ "SplashMessage4", "Parsing Function Definitions..." },
		{ "SqlCommitF5", "Commit F5" },
		{ "SqlConsole", "SQL Console" },
		{ "SqlConsoleComment", "* You can execute RDBMS embedded procedures as well as SQL statements here. But executing CREATE TABLE statement is almost meaningless as the table definition for X-TEA Editor will not be generated. Use 'Create Table Definitions' of Tool menu to create table definitions and modules.　Use button of 'List Modules' to list table modules existing in the DB selected.\n" },
		{ "SqlConsoleMessage1", ". . . Committing succeded.\n(" },
		{ "SqlConsoleMessage2", "Operation failed." },
		{ "SqlListModules", "List Modules" },
		{ "Start", "Start" },
		{ "StartInAddMode", "Adding first if without row" },
		{ "Status", "Status" },
		{ "StrNodeIconField", "Structure Node Icon Field" },
		{ "StrNodeText", "Structure Node Text Field" },
		{ "StrRootText", "Structure Root Icon Field" },
		{ "StrUpperKeyField", "Structure Upper Key Field" },
		{ "StrChildKeyField", "Structure Child Key Field" },
		{ "StructureChildKeys", "Child Keys" },
		{ "StructureNodeDefaultIcon", "Default Icon" },
		{ "StructureNodeIcons", "Node Icons" },
		{ "StructureNodeIconsComment", "Control field is one of physical fields of the header tabel. Number of Icons and field values separated by ';' must be corresponding each other." },
		{ "StructureNodeIconsFieldID", "Control Field" },
		{ "StructureNodeIconsFieldValues", "Field Values" },
		{ "StructureNodeIconsList", "Icon List" },
		{ "StructureNodeIconsTitle", "Config Structure Node Icons" },
		{ "StructureNodeText", "Node Text" },
		{ "StructureNodeTextRemarks", "Specify physical datasouces on the HDR table or structure table\nwith ';' to separate them.Use quotation(') to put fixed string value." },
		{ "StructureOrderBy", "OrderBy" },
		{ "StructureRootText", "Root Text" },
		{ "StructureRootTextRemarks", "Specify physical fieldID on the HDR table with ';' to separate them.\nUse quotation(') to put fixed string value." },
		{ "StructureTable", "Structure Table" },
		{ "StructureTableComment", "'Upper Keys' and 'Child Keys' are corresponding to PK of the parent table." },
		{ "StructureTableTitle", "Config Structure Table" },
		{ "StructureUpperKeys", "Upper Keys" },
		{ "StructureView", "Structure Tree" },
		{ "StructureViewTitle", "Tree View Caption" },
		{ "StructureViewWidth", "Tree View Width" },
		{ "SubDB", "Sub-DB" },
		{ "Subsystem", "Subsystem" },
		{ "SubsystemDescriptions", "Subsystems" },
		{ "SubsystemFunctions", "Fnc" },
		{ "SubsystemID", "Subsystem ID" },
		{ "SubsystemIDAndName", "Subsystem ID/Name" },
		{ "SubsystemImportingFrom", "Subsystem Importing" },
		{ "SubsystemImportingInto", "Importing Into" },
		{ "SystemInfo", "System Information" },
		{ "SystemMaintenanceLog", "Maintenance Log" },
		{ "SystemMaintenanceLogVersion", "Version" },
		{ "SystemMaintenanceLogDateTime", "Date_Time" },
		{ "SystemMaintenanceLogSortKey", "Date_Time" },
		{ "SystemMaintenanceLogRemarks", "Discriptions" },
		{ "SubsystemName", "Subsystem Name" },
		{ "SubsystemRemarks", "Descriptions" },
		{ "SubsystemTables", "Tbl" },
		{ "System", "System" },
		{ "SystemCalendar", "Calendar" },
		{ "SystemDatabaseConfig", "Database Config" },
		{ "SystemOtherConfig", "Other" },
		{ "SystemDefinition", "System Definition" },
		{ "SystemDescriptions", "System" },
		{ "SystemExchangeRateAnnual", "Annual Rate" },
		{ "SystemExchangeRateMonthly", "Monthly Rate" },
		{ "SystemName", "System Name" },
		{ "SystemNameImporting", "System Importing" },
		{ "SystemNumbering", "Numbering" },
		{ "SystemRemarks", "Descriptions" },
		{ "SystemSession", "Session" },
		{ "SystemSessionDetail", "Session Detail" },
		{ "SystemTax", "Tax" },
		{ "SystemUser", "System User" },
		{ "SystemUserFilterValue", "Filter Value" },
		{ "SystemUserVariants", "User Variants" },
		{ "SystemVariants", "Sys. Variants" },
		{ "SystemVersion", "Version" },
		{ "TabbedFields", "Tabbed Fields" },
		{ "Table", "Table" },
		{ "TableDefinition", "Table Definition" },
		{ "TableDefinitions", "Tables" },
		{ "Table/Field", "Table / Field" },
		{ "Table/Script", "Table / Script" },
		{ "TableID", "Table ID" },
		{ "TableIDAndName", "Table Name" },
		{ "TableKey", "Access Key" },
		{ "TableList", "Table List" },
		{ "TableModuleCheck", "Module Check" },
		{ "TableModuleID", "Physical ID" },
		{ "TableName", "Table Name" },
		{ "TableOperation", "Table Operation" },
//		{ "TableReferCheck", "Chross Checking" },
		{ "TableUsageInScript1", "Operated in Script '" },
		{ "TableUsageInScript2", "' (" },
		{ "TableUsageInScript3", ")" },
		{ "TableUsageInScript4", "Operated in Script (" },
		{ "Text", "Text" },
		{ "TimerDefault", "Default Time" },
		{ "TimerMessage", "Message" },
		{ "TipsFunction", "You can change the subsystem of functions. Drag and drop the tree node of function into function list of the target subsystem." },
		{ "TipsMenu", "You can drag and drop the tree node of function\ninto this list to add the function as a menu option." },
		{ "TipsTable", "You can change the subsystem of tables. Drag and drop the tree node of table into table list of the target subsystem." },
		{ "TipsTitle", "Hint to Edit" },
		{ "TipsToEdit", "Tips to edit" },
		{ "Tools", "Tool" },
		{ "Type", "Type" },
		{ "TypeOptions", "Type Options" },
		{ "Undo", "Undo changes in node" },
		{ "UndoAdd", " is newly registered." },
		{ "UndoModify", " is editted." },
		{ "UndoRemove", " is deleted." },
		{ "Update", "Update" },
		{ "UpdateCounter", "Upd.Counter" },
		{ "UpdateList", "Update-List" },
		{ "UpdateMessage", "Execute Msg." },
		{ "UsageBatchFieldPrompter", "Batch Field Prompter" },
		{ "UsageColumnPrompter", "Column Prompter" },
		{ "UsageDTLFunction", "DTL Function" },
		{ "UsageFieldPrompter", "Field Prompter" },
		{ "UsageHDRFunction", "HDR Function" },
		{ "UsageLaunchedAfterInsert", "Launched After Insert" },
		{ "UsageLaunchedByBatchRecord", "Launched By Batch Record" },
		{ "UsageLaunchedByFunctionKey", "Launched By Function Key" },
		{ "UsageLaunchedByRow", "Launched By Detail Rows" },
		{ "UsageLaunchedInScript", "Launched In Script" },
		{ "User", "User" },
		{ "UserID", "User ID" },
		{ "ValueSpecified", "Value" },
		{ "VariantNameOnScript", "Variant name on script" },
		{ "Virtual", "Virtual" },
		{ "WarningMessage1", "Warning: Data source name of this join field\nduplicates with fields of the batch table." },
		{ "WarningMessage2", "Warning: Data source name of this join field\nduplicates with fields of the primary table." },
		{ "WarningMessage3", "Warning: Data source name of this join field\nduplicates with fields of the DTL table." },
		{ "WarningMessage4", "Warning: Data source name of this join field\nduplicates with fields of the HDR table." },
		{ "WelcomePageURL", "Welcome Page" },
		{ "WhereUsed", "Where Used" },
		{ "WhereUsedForm", "Where-Used Form" },
		{ "WhereUsedTable", "Where-Used Table" },
		{ "Width", "Width" },
		{ "WidthRate", "Width Rate" },
		{ "WithTotal", "With Total" },
		{ "XLSComment", "*These rows are filtered or ordered by those criteria：" },
		{ "XLSErrorMessage", "IOException of EXCEL data. Refer to session log for details." },
//		{ "XLSFontDTL", "Times New Roman" },
//		{ "XLSFontHDR", "Arial" },
		{ "Yes", "Yes" }
	};

	public Object[][] getContents() {
		return contents;
	}
}
