package xeadEditor;

/*
 * Copyright (c) 2015 WATANABE kozo <qyf05466@nifty.com>,
 * All rights reserved.
 *
 * This file is part of X-TEA Editor.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the XEAD Project nor the names of its contributors
 *       may be used to endorse or promote products derived from this software
 *       without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

public class Res_ja extends java.util.ListResourceBundle {
	private static final Object[][] contents = new String[][]{
		{ "About", "バージョン情報" },
		{ "AcceptMinus", "マイナス可" },
		{ "Action", "アクション" },
		{ "ActionAddBlankRow", "空白行の追加" },
		{ "ActionAddRows", "明細行の追加" },
		{ "ActionAddRowWithSelected", "選択行で追加" },
		{ "ActionAfterInsert", "追加処理後" },
		{ "ActionBackToSelectList", "更新リストから選択リストへ戻る" },
		{ "ActionCall", "の起動" },
		{ "ActionCallDTLFunctionToAdd", "明細処理機能を追加モードで起動" },
		{ "ActionCallFunction", "指定機能の起動" },
		{ "ActionCallHDRFunction", "見出し処理機能を起動" },
		{ "ActionCallToAddRows", "行追加用機能の起動" },
		{ "ActionDelete", "削除" },
		{ "ActionDeleteHDR", "見出しレコードの削除" },
		{ "ActionExit", "終了" },
		{ "ActionGoToCopyMode", "複写モード移行" },
		{ "ActionGoToEditMode", "編集モード移行及び更新" },
		{ "ActionGoToUpdateList", "選択リストから更新リストに進む" },
		{ "ActionOutputEXCEL", "エクセルに一覧出力" },
		{ "ActionRemoveRow", "明細行の除去" },
		{ "ActionReturnNull", "Nullキーを返す" },
		{ "ActionUpdate", "編集結果で更新" },
		{ "Add", "追加" },
		{ "AddChild", "下位要素を追加" },
		{ "AddFields", "追加フィールドの選択" },
		{ "AddFunction", "機能定義の追加" },
		{ "AddIndex", "インデックスの追加" },
		{ "AddIndexMessage", "物理フィールドＩＤを';'でつなげて指定してください。\nフィールドＩＤの後に'(D)'を置けば降順とみなされます。" },
		{ "AddJoinTable", "結合テーブルの追加" },
		{ "AddJoinTableMessage1", "テーブルＩＤを指定して「次へ」を押してください。必要ならばエイリアスも指定してください。" },
		{ "AddJoinTableMessage2", "「結合先KEY項目」には " },
		{ "AddJoinTableMessage3", "上の項目のIDを指定してください。「結合元KEY項目」には「結合先KEY項目」に対応する " },
		{ "AddJoinTableMessage4", "上の項目または結合済項目のIDを、TABLEID.FIELDID のようにテーブルID付きで指定してください。項目が複数の場合は ; で区切ります。" },
		{ "AddKeyMessage", "フィールドを選択してキーに組み込んでください。" },
		{ "AddMode", "追加モード" },
		{ "AddNewFields", "フィールド定義の新規追加" },
		{ "AddNewMenus", "メニュー定義の新規追加" },
		{ "AddNewSubsystems", "サブシステム定義の新規追加" },
		{ "AddNewTables", "テーブル定義の新規追加" },
		{ "AddPKey", "一次識別子の追加" },
		{ "AddRow", "行追加" },
		{ "AddRowDetailRowNo", "行追加時の自動設定行番" },
		{ "AddRowList", "行追加設定" },
		{ "AddRowListButton", "追加行参照リストの機能キー" },
		{ "AddRowListColumn", "追加行参照リストの明細フィールド" },
		{ "AddRowListFieldsDialogComment", "＊参照リストから追加行への返しフィールドを、いずれもエイリアス付きで指定してください。複数指定する場合はセミコロン(;)で区切ってください。何も指定しない場合、参照リストと明細行とで共通しているフィールドが返しフィールドとみなされます。" },
		{ "AddRowListFieldsDialogTitle", "追加行への返しフィールド設定" },
		{ "AddRowListOrderBy", "追加行参照リスト一覧順" },
		{ "AddRowListReturnFromField", "追加行参照リストからの戻し元フィールド" },
		{ "AddRowListReturnFromFieldShort", "戻し元フィールド" },
		{ "AddRowListReturnToField", "追加行参照リストからの戻し先フィールド" },
		{ "AddRowListReturnToFieldShort", "戻し先フィールド" },
		{ "AddRowListTable", "行追加参照テーブル" },
		{ "AddRowListTableDialogComment", "＊「キー値フィールド」には、検索キーの並びに合わせて見出し域上のフィールドをエイリアス付きで指定してください。" },
		{ "AddRowListTableDialogTitle", "行追加用参照テーブルの設定" },
		{ "AddRowListWithFields", "追加行リスト検索キー" },
		{ "AddRowListWithFieldsShort", "リスト検索キー" },
		{ "AddRowListWithHeaderFields", "追加行参照リストの選択キーフィールド" },
		{ "AddRowListWithHeaderFieldsShort", "キー値フィールド" },
		{ "AddRowListWhere", "追加行リストWhere" }, 
		{ "AddRowListInitialMsg", "追加行リスト初期メッセージ"},
		{ "AddRowListReturnDataSources", "追加行リスト戻し元フィールド"},
		{ "AddRowListReturnToDetailDataSources", "追加行リスト戻し先フィールド"},
		{ "AddSKey", "二次識別子の追加" },
		{ "AddTabDialogComment", "新たな明細テーブル向けのタブが追加されます。見出しテーブルから見て「子」または「参照元」を明細テーブルとして指定してください。" },
		{ "AddTabDialogKeyComment", "「見出しKEY項目」の並びにしたがって「処理KEY項目」に明細テーブル側の処理KEYを、フィールドを';'で区切って指定してください。" },
		{ "AddTabDialogTitle", "明細タブの追加" },
		{ "Alias", "エイリアス" },
		{ "Alignment", "アラインメント" },
		{ "AllSubsystems", "（すべてのサブシステム）" },
		{ "AndSoOn1", "、他" },
		{ "AndSoOn2", "件" },
		{ "AppendCheckDeleteError1", "既存の" },
		{ "AppendCheckDeleteError2", "によって参照されているため、このレコードは削除できません。" },
		{ "AppendCheckDeleteMessage", "このテーブルに対する結合定義にもとづく削除チェック用ルーチンを付加しますか？" },
		{ "AppendCheckDeleteTitle", "削除チェックの組込確認" },
		{ "AppendCheckDeleteWarning", "付加されたスクリプトはエラーを含んでいます。Error!のついた行を修正してください。" },
		{ "Application", "アプリケーション" },
		{ "AppServerName", "DBメソッドURL" },
		{ "AskIfReplacing", "指定されたファイルは既に存在します。上書きしますか？" },
		{ "AttributeName", "属性名" },
		{ "AttributeType", "属性区分" },
		{ "AttributeValue", "属性値" },
		{ "AutoConnect", "Editor起動時にＤＢ接続する" },
		{ "AutoNumberID", "自動採番値" },
		{ "AutoRowNumber", "Auto行番" },
		{ "BackToEdit", "編集に戻る" },
		{ "BackupFile", "バックアップの確認" },
		{ "BackupFileMessage", "更新前のシステム定義ファイルをバックアップしますか？" },
		{ "BarcodeType", "バーコードタイプ" },
		{ "BatchField", "バッチフィールド" },
		{ "BatchKey", "バッチ条件" },
		{ "BatchKeyAbout", "＊「バッチ条件」とは、一次テーブル上の複数の更新レコードをバッチテーブルの新規レコードに関連付けるためのフィールド一致条件のことです。それぞれのテーブルのバッチ条件フィールドをセミコロンで区切って並べてください。一次テーブル側の条件についてはエイリアス指定が必要です。" },
		{ "BatchKeyField", "バッチテーブル側のバッチ条件" },
		{ "BatchRecordCallID", "バッチ機能ＩＤ" },
		{ "BatchRecordCallMsg", "実行確認Check" },
		{ "BatchTable", "バッチテーブル" },
		{ "BatchTableDialogTitle", "バッチテーブルとバッチ条件の設定" },
		{ "BatchWithKeyField", "一次テーブル側のバッチ条件" },
		{ "Bookmark", "しおりの設定・解除" },
		{ "Both", "両方" },
		{ "Bracket1", "「" },
		{ "Bracket2", "」" },
		{ "BrowseHelp", "概要と目次" },
		{ "Button", "機能キー" },
		{ "ButtonPositionComment", "０（左端）～６（右端）" },
		{ "ButtonPositionComment0_5", "０（左端）～５（右端）" },
		{ "ByteaType", "ファイルタイプフィールド" },
		{ "CallFunction", "機能を起動" },
		{ "CallModeler", "Modelerの起動" },
		{ "CallPromptFunction", "指定機能" },
		{ "Cancel", "取消" },
		{ "CancelChanges", "保存しない" },
		{ "Caption", "キャプション" },
		{ "CaptionErrorMessage", "キャプション値として '('  ')'  ',' は使えません。" },
		{ "CaptionLengthVariable", "可変長キャプション" },
		{ "CaseSensitive", "大文字小文字を区別する" },
		{ "Changed", "変更あり" },
		{ "ChangeLabel", "ID⇔名称" },
		{ "CheckAllItems", "全体"},
		{ "CheckAllModules", "モジュールの一括作成"},
		{ "CheckAllModulesMessage1", "未作成分のテーブルモジュールが存在しません。"},
		{ "CheckAllModulesMessage2", "未作成分のテーブルモジュールが一括作成されます。"},
		{ "CheckContinueAdding", "継続追加"},
		{ "CheckFunctionsCalled", "機能関連性検査"},
		{ "CheckFunctionsCalledMessage1", "機能関連上の問題は見つかりませんでした。"},
		{ "CheckFunctionsCalledMessage2", "いずれの定義要素からも起動されません。"},
		{ "CheckFunctionsCalledMessage3", "スクリプト中で記述されているID '"},
		{ "CheckFunctionsCalledMessage4", "' が機能として存在しません。"},
		{ "CheckFunctionsCalledMessage5", "起動される機能 '"},
		{ "CheckFunctionsCalledMessage6", "' が存在しません。"},
		{ "CheckFunctionsCalledMessage7", "スクリプト「"},
		{ "CheckFunctionsCalledMessage8", "」中で記述されているID '"},
		{ "CheckFunctionsCalledMessage9", "' が機能として存在しません。"},
		{ "CheckFunctionsCalledMessage10", "追加ボタンでの呼び出しが設定されていますが、明細処理機能が設定されていません。"},
		{ "CheckFunctionsCalledMessage11", "見出しレコード処理用ボタンが設定されていますが、見出し処理機能が設定されていません。"},
		{ "CheckFunctionsCalledMessage12", "クロスチェッカーのIDが正しくありません。"},
		{ "CheckFunctionsCalledMessage13", "プリロード機能のIDが正しくありません。"},
		{ "CheckLayout", "レイアウト確認"},
		{ "CheckLayoutTitle", "パネルレイアウトの確認"},
		{ "CheckMark", "ｖ"},
		{ "CheckUpdateOnly", "更新専用"},
		{ "ChooseAction", "閲覧・編集されるファイルが指定されていません。定義を新規作成したい場合\nは、Skeleton.xeaf をコピーしてリネームしたものを用いてください。" },
		{ "ChooseXeadFile", "インポート元となるモデル情報ファイル(*.xead)を選択してください。" },
		{ "ChooseXeafFile", "インポート元となるシステム定義ファイル(*.xeaf)を選択してください。" },
		{ "ChooseXeafFileToDiff", "比較の起点とすべきシステム定義ファイル(*.xeaf)を選択してください。" },
		{ "ClearValues", "値クリア" },
		{ "Close", "閉じる" },
		{ "CloseNotSaving", "保存せずに閉じる" },
		{ "CloseSaving", "保存して閉じる" },
		{ "ColumnOnList", "表示リスト" },
		{ "Column", "明細フィールド" },
		{ "Columns", "明細フィールド" },
		{ "Comma", "、" },
		{ "Comment", "コメント" },
		{ "Commit", "コミット" },
		{ "CommitCheck", "コミットの確認" },
		{ "CommitCheckMessage", "データ保守ユーティリティで更新が保留されています。コミットしますか？" },
		{ "Compress", "COMPRESS" },
		{ "Connection", "ＤＢ接続" },
		{ "ConsoleOption", "コンソール" },
		{ "ConsoleOptionYes", "あり" },
		{ "ConsoleOptionTimer", "タイマー" },
		{ "ControlOptions", "制御オプション" },
		{ "CopiedNameExt", "(コピー)" },
		{ "Copy", "コピー" },
		{ "CopyToClipboard", "クリップボードにコピー" },
		{ "CreateDefinition", "定義作成" },
		{ "CreateInSubsystem", "作成先サブシステム" },
		{ "CreateTableComment", "＊CREATE文を用いてテーブル定義を１個ずつ作成できます。テーブル定義のみが作成されるので、定義を編集し完成させたうえで、個別にテーブルモジュールを作成してください。ここではFOREIGN KEY制約句は無視され、有効なデータ型は以下のとおりです。CHAR,VARCHAR,TEXT,INTEGER,SMALLINT,BIGINT,DOUBLE,DECIMAL,NUMERIC,REAL,DATE,TIME,TIMETZ,TIMESTAMP,TIMESTAMPTZ（詳しくはヘルプを参照してください）。以下はCREATE文の例です。\n\nCreate table AT010 (\n  CDBUMON CHAR(5) Not null Comment \'部門Ｃ\',\n  TXBUMON CHAR(30) Not null Comment \'部門名\',\n  NRKANRISYA CHAR(5) Not null Comment \'管理者№\',\n  TXTEKIYO VARCHAR(300) Comment \'摘要\',\n  Constraint AT010_PK Primary key (CDBUMON)\n)" },
		{ "CreateTableDef", "テーブル定義作成" },
		{ "CreateTableStatement", "CREATE TABLE文" },
		{ "CreateTableTitle", "CREATE文を用いたテーブル定義作成" },
		{ "Data", "データ" },
		{ "Database", "データベース" },
		{ "DatabaseMain", "メインＤＢ" },
		{ "DatabaseSub", "サブＤＢ" },
		{ "DatabaseSubReadOnly", "サブＤＢ（読取専用）" },
		{ "DataMessages", "必要に応じてWhere条件とOrderByを指定したうえで、検索ボタンを押してください。" },
		{ "DataName", "データ名" },
		{ "DataOutput", "EXCEL出力" },
		{ "DataSource", "データソース" },
		{ "DataType", "データタイプ" },
		{ "DataUtilityMessage1", "必要に応じて値を入力して「コミット」を押してください。" },
		{ "DataUtilityMessage2", "データが正常に更新されました。" },
		{ "DataUtilityMessage3", "＊このデータを読み取って更新するまでの間に、他の操作または\nユーザによって更新されました。要求はキャンセルされました。" },
		{ "DataUtilityMessage4", "指定のキー値を持つデータが既に存在しています。追加できません。" },
		{ "DataUtilityMessage5", "データが正常に追加されました。" },
		{ "DataUtilityMessage6", "データが正常に削除されました。" },
		{ "DataUtilityMessage7", "テーブルが圧縮されました。" },
		{ "DataUtilityMessage8", "このテーブルにはこの操作を実行できません。" },
		{ "DateFormat", "日付形式" },
		{ "DBConnect", "データベース接続" },
		{ "DBConnectMessage0", "X-TEA Editor - データベースサービスの確認" },
		{ "DBConnectMessage1", " " },
		{ "DBConnectMessage2", "\nへ接続できませんでした。必要ならばＤＢサービスを開始したうえで「再試行」を押してください。\nツールメニューから後で接続することもできます。" },
		{ "DBConnectMessage3", "再試行 " },
		{ "DBConnectMessage4", "今は接続しない" },
		{ "DBConnectMessage5", "データベースに接続されるとともに、全テーブル定義に\nついてモジュールチェックがなされます。接続しますか？" },
		{ "DBConnectMessage6", "接続中..." },
		{ "DBConnectMessage7", "エラー詳細" },
		{ "DBConnectMessage8", "データベースに接続されました。" },
		{ "DBConnectMessage9", "データベースにアクセスできません。回線状態を確認したうえで、ツールメニューの「データベース接続」を実行してください。" },
		{ "DBCPOptions", "DBCPオプション" },
		{ "Decimal", "小数桁" },
		{ "Delete", "削除" },
		{ "DeleteCanceled", "削除要求が取り消されました。" },
		{ "DeleteCheckMessage", "この行を削除します。よろしいですか？" },
		{ "DeleteCheckTitle", "削除確認" },
		{ "DeleteFunction", "機能定義の削除確認" },
		{ "DeleteTableDefinitionAndModule", "モジュールと定義を削除" },
		{ "DeleteTableDefinitionOnly", "定義のみを削除" },
		{ "DeleteTableMessage", "テーブルモジュールが存在します。定義とともにモジュールを削除しますか？" },
		{ "DeleteTableModule", "モジュールの削除確認" },
		{ "Descent", "(降順)" },
		{ "Descriptions", "摘要" },
		{ "Detail", "明細タブ" },
		{ "DetailFunction", "明細機能" },
		{ "DetailRowNumber", "最後のフィールドをAuto行番として処理する" },
		{ "DetailRowNumberAuto", "Auto行番設定" },
		{ "DetailTable", "明細テーブル" },
		{ "DriverVMOptions", "VMオプション" },
		{ "DTLField", "明細フィールド" },
		{ "DTLFields", "明細フィールド" },
		{ "DTLFont", "明細フォント" },
		{ "DTLFunction", "明細処理機能" },
		{ "DTLFunctionID", "明細処理機能ID" },
		{ "DTLTable", "明細テーブル" },
		{ "DTLTableID", "明細テーブルID" },
		{ "DTLTableKeys", "明細KEY" },
		{ "DTLTabs", "明細タブ" },
		{ "Edit", "編集" },
		{ "Editable", "入力可" },
		{ "EditableOptions", "入力オプション" },
		{ "EditCode", "編集コード" },
		{ "EditDetailTableKeyTitle", "明細テーブルと処理キーの変更" },
		{ "EditDetailTableKeyComment", "見出しKEY（見出しテーブルの処理キー）と明細KEY（明細テーブルの処理キー）の上位共通部分のデータタイプは同一でなければなりません。" },
		{ "EditKeyFieldsToPutIntoKey", "キーに組み込む"},
		{ "EditKeyFieldsToGoUp", "上へ"},
		{ "EditKeyFieldsToGoDown", "下へ"},
		{ "EditKeyFieldsToSetAscDesc", "昇降切替"},
		{ "EditKeyFieldsToRemove", "はずす"},
		{ "EditMode", "編集モード" },
		{ "EditOrderByMessage", "テーブルＩＤとフィールドＩＤを'.'でつなげて指定してください。フィールドＩＤの後に'(D)'を置けば\n降順とみなされます。複数項目を指定する場合は';'で区切って並べてください。" },
		{ "EditorUser", "Editor ユーザ" },
//		{ "EditRangeKeyMessage", "テーブル上のデータタイプが同一のフィールドＩＤを';'でつなげて指定してください。" },
		{ "EditReferWithKeyMessage", "結合テーブルのキー構成に合わせて、先行して取得されているフィールドを組み合わせて指定して\nください。複数項目を指定する場合は';'で区切って並べてください。" },
		{ "EditTableKeyTitle", "テーブルと処理キーの変更" },
		{ "EditTableScript", "大きなエディタ上で編集" },
		{ "EditTableScriptTitle", "テーブル・スクリプトの編集" },
		{ "EditTypeNormal", "通常編集" },
		{ "EditTypeNoEdit", "編集なし" },
		{ "EditTypeZeroSuppress", "ゼロサプレス" },
		{ "EditTypeHourMinuite", "時刻(HH:MM)" },
		{ "ElementName", "定義要素名" },
		{ "ElementType", "定義要素区分" },
		{ "ElementStatus", "比較状況" },
		{ "EOL", "この後で改行" },
		{ "ErrorLog1", "エラーログ " },
		{ "ErrorLog2", " が発行されました。" },
		{ "ErrorMessage1", "[" },
		{ "ErrorMessage2", "]のエラーが発生しました。\n詳細については、終了時に出力されるエラーログファイル(xeadedt_err_....txt)を参照してください。" },
		{ "ErrorMessage3", "エラー：ID'" },
		{ "ErrorMessage4", "'のフィールドが存在しません。" },
		{ "ErrorMessage5", "エラー：指定されたフィールドのデータタイプが整数でありません。" },
		{ "ErrorMessage6", "エラー：１つ目の項目定義が無効です。" },
		{ "ErrorMessage7", "エラー：２つ目の項目定義が無効です。" },
		{ "ErrorMessage8", "エラー：同一項目が指定されています。" },
		{ "ErrorMessage9", "エラー：タイプと長さが同一の項目を指定してください。" },
		{ "ErrorMessage10", "エラー：１つ目の項目はテーブルの一次識別子に含まれていなければなりません。" },
		{ "ErrorMessage11", "指定値'" },
		{ "ErrorMessage12", "'の形式が正しくないか、フィールド定義が存在しません。" },
		{ "ErrorMessage13", "適正範囲内(" },
		{ "ErrorMessage14", ")でないサイズが指定されました。値は無視されます。" },
		{ "ErrorMessage15", "数値でないサイズが指定されました。値は無視されます。" },
		{ "ErrorMessage16", "ID='" },
		{ "ErrorMessage17", "'の定義要素が既に存在しています。この要素は追加されません。" },
		{ "ErrorMessage18", "ID='" },
		{ "ErrorMessage19", "'のテーブル定義が既にこのサブシステム\nまたは他のサブシステムの下に存在しています。\nこの要素は追加されません。" },
		{ "ErrorMessage20", "このサブシステムにはテーブル定義か機能定義が含まれているため、削除できません。" },
		{ "ErrorMessage21", "このテーブルを利用する機能か結合テーブルが存在します。それらをはずしたうえで削除してください。" },
		{ "ErrorMessage22", "この機能はすでにメニューオプションとして組み込まれています。" },
		{ "ErrorMessage23", "メニューにオプションを追加する余地がありません。" },
		{ "ErrorMessage24", "マージンの値が正しくありません。省略値(50;50;50;50)に設定されました。" },
		{ "ErrorMessage25", "コマンド " },
		{ "ErrorMessage26", " を実行できませんでした。\n" },
		{ "ErrorMessage27", "ヘルプファイルを開けません。" },
		{ "ErrorMessage28", "保存できませんでした。" },
		{ "ErrorMessage29", "このフォントを利用する機能が存在します。それらをはずしたうえで削除してください。" },
		{ "ErrorMessage30", "削除不可。少なくとも１件の要素が必要です。" },
		{ "ErrorMessage31", "この定義要素に関連する機能か結合テーブルが存在します。それらをはずしたうえで削除してください。" },
		{ "ErrorMessage32", "" },
		{ "ErrorMessage33", "件のフィールドが結合フィールドとして利用されているため削除できません。\nフィールド名をクリックすれば、どの定義要素によって利用されているかが示されます。" },
		{ "ErrorMessage34", "この機能はいずれかの定義要素によって利用されています。削除しますか？" },
		{ "ErrorMessage35", "X-TEA Modelerコンテンツファイルを開けません。" },
		{ "ErrorMessage36", "この機能は、メニュー（" },
		{ "ErrorMessage37", "）に組み込まれているため、削除できません。" },
		{ "ErrorMessage38", "正しくない結合順序が指定されることになります。要求は無視されます。\n（各結合テーブルの処理キー項目の値が、先行する読取によって確保されている必要があります）" },
		{ "ErrorMessage39", "このテーブルを利用する機能、または結合テーブルとして利用\nするテーブルが存在するので、PKの変更は認可されません。" },
		{ "ErrorMessage40", "エラー：バッチテーブル側の条件にエイリアス指定は不要です。" },
		{ "ErrorMessage41", "エラー：一次テーブルのバッチ条件指定が正しくありません：" },
		{ "ErrorMessage42", "エラー：バッチテーブルのバッチ条件に指定されたフィールドＩＤが正しくありません：" },
		{ "ErrorMessage43", "エラー：対応するバッチ条件フィールドで、項目タイプ／桁が異なっている部分があります：" },
		{ "ErrorMessage44", "エラー：一次テーブルのバッチ条件には、エイリアス（テーブルＩＤ）とフィールドＩＤとをピリオド(.)で区切って指定してください。" },
		{ "ErrorMessage45", "エラー：バッチ条件の項目数が一次テーブルとバッチテーブルとで一致していません。" },
		{ "ErrorMessage46", "エラー：リスト検索キーにエイリアス指定は不要です。" },
		{ "ErrorMessage47", "エラー：リスト検索キーに指定されたフィールドＩＤが正しくありません。" },
		{ "ErrorMessage48", "エラー：キー値フィールドが存在しません。" },
		{ "ErrorMessage49", "エラー：キー項目間で、項目タイプ／桁が異なっている部分があります。" },
		{ "ErrorMessage50", "エラー：キー値フィールドには、見出しテーブル上のフィールドか結合フィールドのいずれかを指定してください。" },
		{ "ErrorMessage51", "エラー：キー値フィールドはエイリアス指定でなければなりません。" },
		{ "ErrorMessage52", "エラー：リスト検索キーとキー値フィールドとの項目数が一致していません。" },
		{ "ErrorMessage53", "エラー：戻し元フィールドの指定が正しくありません。" },
		{ "ErrorMessage54", "エラー：戻し先フィールドの指定が正しくありません。" },
		{ "ErrorMessage55", "エラー：キー項目間で、項目タイプ／桁が異なっている部分があります。" },
		{ "ErrorMessage56", "エラー：戻し先フィールドには、エイリアス（テーブルＩＤ）とフィールドＩＤとをピリオド(.)で区切って指定してください。" },
		{ "ErrorMessage57", "エラー：戻し元フィールドには、エイリアス（テーブルＩＤ）とフィールドＩＤとをピリオド(.)で区切って指定してください。" },
		{ "ErrorMessage58", "エラー：戻し元と戻し先とで項目数が一致していません。" },
		{ "ErrorMessage59", "エラー：渡し元フィールドの指定値 " },
		{ "ErrorMessage60", " に対応するデータソース定義が存在しません。" },
		{ "ErrorMessage61", "エラー：渡し元フィールドには、エイリアス（テーブルＩＤ）とフィールドＩＤとをピリオド(.)で区切って指定してください。" },
		//{ "ErrorMessage62", "エラー：渡し先フィールドの指定値 " },
		//{ "ErrorMessage63", " に対応するデータソース定義が存在しません。" },
		{ "ErrorMessage64", "エラー：渡し先フィールドには、エイリアス（テーブルＩＤ）とフィールドＩＤとをピリオド(.)で区切って指定してください。" },
		{ "ErrorMessage65", "エラー：渡しフィールドの数が元と先とで一致していません。" },
		{ "ErrorMessage66", "エラー：返しフィールドの数が元と先とで一致していません。" },
		//{ "ErrorMessage67", "エラー：返し元フィールドの指定値 " },
		//{ "ErrorMessage68", " に対応するデータソース定義が存在しません。" },
		{ "ErrorMessage69", "エラー：返し元フィールドには、エイリアス（テーブルＩＤ）とフィールドＩＤとをピリオド(.)で区切って指定してください。" },
		{ "ErrorMessage70", "エラー：返し先フィールドの指定値 " },
		{ "ErrorMessage71", " に対応するデータソース定義が存在しません。" },
		{ "ErrorMessage72", "エラー：返し先フィールドには、エイリアス（テーブルＩＤ）とフィールドＩＤとをピリオド(.)で区切って指定してください。" },
		{ "ErrorMessage73", "エラー：明細KEY項目を指定してください。" },
		{ "ErrorMessage74", "エラー：明細KEY項目は見出しKEY項目より多く指定されなければなりません。" },
		{ "ErrorMessage75", "エラー：ID'" },
		{ "ErrorMessage76", "'のフィールド定義が存在しません。" },
		{ "ErrorMessage77", "エラー：対応する上位キー項目のタイプか長さが一致していません。" },
		{ "ErrorMessage78", "エラー：機能IDを入力してください。" },
		{ "ErrorMessage79", "エラー：機能タイプを選択してください。" },
		{ "ErrorMessage80", "エラー：機能名を入力してください。" },
		{ "ErrorMessage81", "エラー：このIDを持つ機能定義が既にこのサブシステムまたは\n他のサブシステムの下に存在しています。" },
		{ "ErrorMessage82", "指定テーブルに一次識別子が定義されていないため、機能を作成できません。" },
		{ "ErrorMessage83", "見出しテーブルに一次識別子が定義されていないため、機能を作成できません。" },
		{ "ErrorMessage84", "明細テーブルに一次識別子が定義されていないため、機能を作成できません。" },
		{ "ErrorMessage85", "エラー：見出しテーブルか明細テーブルにキーが定義されていません。" },
		{ "ErrorMessage86", "一次テーブル上の物理フィールドＩＤを';'でつなげて指定してください。" },
		{ "ErrorMessage87", "フィールドＩＤが正しくありません。" },
		{ "ErrorMessage88", "見出しテーブル上の物理フィールドＩＤを';'でつなげて指定してください。" },
		{ "ErrorMessage89", "明細テーブル上の物理フィールドＩＤを';'でつなげて指定してください。" },
		{ "ErrorMessage90", "テーブルＩＤが正しくありません。" },
		{ "ErrorMessage91", "指定のテーブルは既に結合テーブルとして組み込まれています。\nエイリアスを指定して重複を避けてください。" },
		{ "ErrorMessage92", "キー項目をいずれも指定してください。" },
		{ "ErrorMessage93", "キー項目の数が一致していません。" },
		{ "ErrorMessage94", "エラー：対応するキー項目のタイプか長さが一致していません。" },
		{ "ErrorMessage95", "１桁目に半角英文字以外は使えません。" },
		{ "ErrorMessage96", "半角英数字のみを用いてください。" },
		{ "ErrorMessage97", "エラー：テーブル定義は作成されませんでした。CREATE文に間違いがあります。" },
		{ "ErrorMessage98", "" },
		{ "ErrorMessage99", "のテーブル定義が作成されました。" },
		{ "ErrorMessage100", "" },
		{ "ErrorMessage101", "のテーブル定義は、このサブシステムまたは他のサブシステムにおいて既存です。定義は作成されませんでした。" },
		{ "ErrorMessage102", "" },
		{ "ErrorMessage103", "のタイプ " },
		{ "ErrorMessage104", " が無効です。フィールド定義として取り込まれません。" },
		{ "ErrorMessage105", "アンダーバー'_'は使えません。" },
		{ "ErrorMessage106", "エラー：見出しKEY項目を指定してください。" },
		{ "ErrorMessage107", "このＤＢが指定されたテーブル定義が存在します。指定をはずしたうえで削除してください。" },
		{ "ErrorMessage108", "データソース名が正しくありません。" },
		{ "ErrorMessage109", "フィールドＩＤをテーブルＩＤで修飾する必要はありません。" },
		{ "ErrorMessage110", "構成上位キーの指定が正しくありません。" },
		{ "ErrorMessage111", "見出しテーブルのキーと構成上位キーのタイプが異なります。" },
		{ "ErrorMessage112", "再帰キーの指定が正しくありません。" },
		{ "ErrorMessage113", "見出しテーブルのキーと再帰キーのタイプが異なります。" },
		{ "ErrorMessage114", "構成ビューの幅が正しくありません。デフォルト値に設定されます" },
		{ "ErrorMessage115", "フィールドＩＤを１個だけ指定してください。" },
		{ "ErrorMessage116", "アイコンの制御条件が正しくありません。" },
		{ "ErrorMessage117", "構成一覧順の指定が正しくありません。" },
		{ "ErrorMessage118", "既存のテーブルIDはエイリアスとして指定できません。" },
		{ "ErrorMessage119", "指定値でテーブルＩＤを置き換えた場合、以下の未定義フィールドが生じます。\n" },
		{ "ErrorMessage120", "これらを機能定義上で整理したうえで再試行してください。" },
		{ "ErrorMessage121", "フィールドＩＤが正しくありません。" },
		{ "ErrorMessage122", "この変更にともなって「ノードテキスト」の指定が無効になります。" },
		{ "ErrorMessage123", "構成テーブルが指定されているため、この変更は認可されません。" },
		{ "ErrorMessage124", "テーブルモジュールが存在するため、PKの変更は認可されません。「モジュール\nチェック」のオプションを用いてモジュールを削除したうえで、再試行してください。" },
		{ "ErrorMessage125", "次のスクリプトの実行タイミングとして指定されているため、この結合テーブルは削除できません。" },
		{ "ErrorMessage126", "機能ＩＤが正しくありません。" },
		{ "ErrorMessage127", "ＩＤの長さが規定桁以上です。" },
		{ "ErrorMessage128", "NAMEモードでは編集できません。" },
		{ "ErrorMessage129", "バックアップできませんでした。" },
		{ "EventAC", "追加後" },
		{ "EventAD", "削除後" },
		{ "EventAR", "読込後" },
		{ "EventAU", "更新後" },
		{ "EventBC", "追加前" },
		{ "EventBD", "削除前" },
		{ "EventBR", "読込前" },
		{ "EventBU", "更新前" },
		{ "EventReferAR", "全結合テーブルの読込後" },
		{ "EventReferAR1", "「" },
		{ "EventReferAR2", "」の読込後" },
		{ "EventReferAS", "明細データの処理後" },
		{ "EventReferBR", "全結合テーブルの読込前" },
		{ "EventReferBR1", "「" },
		{ "EventReferBR2", "」の読込前" },
		{ "ExchangeParms", "交換" },
		{ "ExchangeFields", "関数交換フィールド" },
		{ "Execute", "実行" },
		{ "ExecuteWhen", "実行タイミング" },
		{ "ExecuteWhenJoin", "実行タイミング（関連テーブル操作）" },
		{ "Exit", "終了" },
		{ "ExitMessage", "編集結果を保存して終了しますか？" },
		{ "ExitNotSaving", "保存せずに終了" },
		{ "ExitSaving", "保存して終了" },
		{ "ExtentionInvalid", "指定ファイルの拡張子が無効です。" },
		{ "F3ToScan", "検索F3" },
		{ "FailedToParse", "指定されたxeafファイルの解析に失敗しました。様式を確認してください" },
		{ "Field", "フィールド" },
		{ "FieldAccountDate", "会計日付" },
		{ "FieldBoolean", "ブール値" },
		{ "FieldColumnName", "カラム名" },
		{ "FieldColumnName2", "カラム名" },
		{ "FieldDialNo", "電話番号" },
		{ "FieldExtType", "拡張データタイプ" },
		{ "FieldFiscalYear", "年度" },
		{ "FieldID", "フィールドID" },
		{ "FieldImageFile", "画像ファイル" },
		{ "FieldKana", "半角カナ" },
		{ "FieldKanji", "漢字" },
		{ "FieldKubunID", "区分値" },
		{ "FieldMargin", "間隔" },
		{ "FieldMonthSeq", "月序" },
		{ "FieldName", "フィールド名" },
		{ "FieldOptions", "設定" },
		{ "FieldRows", "行数" },
		{ "Fields", "フィールド" },
		{ "FieldSize", "桁数" },
		{ "FieldsToExchangeComment", "＊関数へ渡すフィールドと関数から返すフィールド（受け取るフィールド）を指定してください。複数指定する場合はセミコロン(;)で区切ってください。" },
		{ "FieldsToExchangeDialog", "プロンプタ関数との交換フィールド設定" },
		{ "FieldsToGet", "返し元フィールド" },
		{ "FieldsToGetTo", "先フィールド" },
		{ "FieldsToPut", "渡し元フィールド" },
		{ "FieldsToPutTo", "先フィールド" },
		{ "FieldType", "データタイプ" },
		{ "FieldURL", "ＵＲＬ" },
		{ "FieldUsageInScript1", "スクリプト「" },
		{ "FieldUsageInScript2", "」中の変数" },
		{ "FieldUsageInScript3", "スクリプト中の変数" },
		//{ "FieldUsageMessage", "は以下の定義要素で利用されています。\n\n" },
		{ "FieldUsageMessage1", "" },
		{ "FieldUsageMessage2", "の利用状況" },
		{ "FieldUsageToKeyField", "結合テーブルの参照KEY" },
		{ "FieldUsageWithKeyField1", "結合テーブル" },
		{ "FieldUsageWithKeyField2", "への処理KEY" },
		{ "FieldValueList", "リスト値" },
		{ "FieldWidth", "表示幅" },
		{ "FieldYearMonth", "年月" },
		{ "FieldZipNo", "郵便番号" },
		{ "FieldZipAdrs", "〒連動住所" },
		{ "File", "ファイル" },
		{ "FileDiff", "差異レポート" },
		{ "FileDiffMessage", "指定のモデルファイルを起点として、どのような変更がなされたかが示されます。スタートボタンを押してください"},
		{ "FileDiffMessage01", "が変更された"},
		{ "FileDiffMessage02", "の"},
		{ "FileDiffMessage03", "が「"},
		{ "FileDiffMessage04", "」から「"},
		{ "FileDiffMessage05", "」に変更された"},
		{ "FileDiffMessage06", "「"},
		{ "FileDiffMessage07", "」"},
		{ "FileDiffMessage08", "が追加された"},
		{ "FileDiffMessage09", "が削除された"},
		{ "FileDiffMessage10", "件の差異が見つかりました。"},
		{ "FileDiffMessage11", "のフィールド構成が変更された"},
		{ "FileDiffMessage12", "の検索フィールド構成が変更された"},
		{ "FileDiffMessage13", "機能キー構成が変更された"},
		{ "FileDiffNone", "差異なし"},
		{ "FileDiffTargetFile", "起点ファイル"},
		{ "FileDiffTargetSystem", "起点システム名"},
		{ "FileDiffTitle", "ファイル間差異レポート" },
		{ "FileNameImporting", "インポート元ファイル" },
		{ "FileSpecifiedNotFound", "有効な拡張子を持つ指定名のファイルが見つかりません。" },
		{ "FileUpdateMessage", "ファイルを開いた後に、別のユーザによって更新されています。保存しますか？" },
		{ "FilterOfDetailList", "一覧検索条件フィールド" },
		{ "FilterOption", "検査オプション" },
		{ "Filter", "検索条件" },
		{ "Filters", "検索条件" },
		{ "FixedWhere", "固定Where" },
		{ "FixedWhereDTL", "明細固定Where" },
		{ "FixedWhereHDR", "見出し固定Where" },
		{ "Font", "フォント" },
		{ "FontSize", "サイズ" },
		{ "FontStyle", "スタイル" },
		{ "FontStyleBold", "太字" },
		{ "FontStyleBoldItalic", "太字斜字体" },
		{ "FontStyleItalic", "斜字体" },
		{ "FontStyleNormal", "通常" },
		{ "FontStyleUnderlined", "下線" },
		{ "FormatVersionError1", "指定ファイルのフォーマットバージョンは " },
		{ "FormatVersionError2", " ですが、このバージョンのX-TEA Editor\nが扱えるのは " },
		{ "FormatVersionError3", " までです。最新の X-TEA Editor をご利用ください。" },
		{ "FunctionDefinition", "機能定義" },
		{ "FunctionDefinitions", "機能定義" },
		{ "FunctionID", "機能ID" },
		{ "FunctionKeyNo", "機能キー№" },
		{ "FunctionKeys", "機能キー" },
		{ "FunctionList", "機能一覧" },
		{ "FunctionName", "機能名" },
		{ "FunctionsWhereUsed", "使途機能" },
		{ "FunctionType", "機能タイプ" },
		{ "FunctionTypeXF000", "XF000 Scriptランチャー" },
		{ "FunctionTypeXF010", "XF010 Scriptランチャー#1" },
		{ "FunctionTypeXF100", "XF100 明細一括表示" },
		{ "FunctionTypeXF110", "XF110 明細一括保守" },
		{ "FunctionTypeXF200", "XF200 単票表示保守" },
		{ "FunctionTypeXF210", "XF210 単票更新" },
		{ "FunctionTypeXF290", "XF290 単票印刷" },
		{ "FunctionTypeXF300", "XF300 見出し明細表示" },
		{ "FunctionTypeXF310", "XF310 見出し明細保守" },
		{ "FunctionTypeXF390", "XF390 見出し明細印刷" },
		{ "Function/AddRowListButton", "機能定義／追加行リストボタン" },
		{ "Function/AddRowListField", "機能定義／追加行リストフィールド" },
		{ "Function/BatchField", "機能定義／バッチフィールド" },
		{ "Function/Button", "機能定義／ボタン" },
		{ "Function/DTLButton", "機能定義／明細ボタン" },
		{ "Function/DTLField", "機能定義／明細フィールド" },
		{ "Function/DTLTab", "機能定義／明細タブ" },
		{ "Function/Field", "機能定義／フィールド" },
		{ "Function/FieldTab", "機能定義／フィールドタブ" },
		{ "Function/Filter", "機能定義／フィルタ" },
		{ "Function/HDRField", "機能定義／見出しフィールド" },
		{ "Function/HDRPhrase", "機能定義／見出しフレーズ" },
		{ "Function/Phrase", "機能定義／フレーズ" },
		{ "GenerateList", "一覧出力" },
		{ "HashFormat", "ハッシュ方式" },
		{ "HashFormatMessage1", "＊指定されたハッシュ方式にもとづくハッシュ値を確認できます。元値を指定してHashのボタンを押してください。" },
		{ "HashFormatMessage2", "＊ハッシュ方式の指定が正しくありません。ハッシュアルゴリズム、展開回数（数値）、ソルト値付加(true/false)を;(セミコロン)でつなげてください。各要素のデフォルト値は、MD5,1,falseです。" },
		{ "HashFormatSalt", "ソルト値" },
		{ "HashFormatTitle", "ハッシュ方式の確認" },
		{ "HashFormatValue", "元値" },
		{ "HDRData", "見出し情報" },
		{ "HDRField", "見出し域フィールド" },
		{ "HDRFields", "見出しフィールド" },
		{ "HDRFunctionID", "見出し処理機能ID" },
		{ "HDRTable", "見出しテーブル" },
		{ "HDRTableKeys", "見出しKEY" },
		{ "HeaderFunction", "見出し処理機能" },
		{ "HeaderParmAdditional", "見出し処理機能の追加交換値" },
		{ "HeaderTable", "見出しテーブル" },
		{ "Height", "高さ" },
		{ "Help", "ヘルプ" },
		{ "Hidden", "非表示" },
		{ "HitCount", "Hit" },
		{ "ID", "ＩＤ" },
		{ "IDAndName", "ID/名称" },
		{ "IDWithLength1", "ID(最長" },
		{ "IDWithLength2", "桁)" },
		{ "IgnoreIfZero", "0ならば無視" },
		{ "ImageFolder", "画像フォルダ" },
		{ "Import", "インポート" },
		//{ "ImportCsv", "CSVデータのインポート" },
		//{ "ImportCsvMessage1", "インポート処理が完了しました。" },
		//{ "ImportCsvMessage2", "件が追加され、" },
		//{ "ImportCsvMessage3", "件についてはキー値が既存であるために追加されませんでした。" },
		//{ "ImportCsvMessage4", "ERROR: CSVのデータ形式が正しくありません。" },
		//{ "ImportCsvMessage5", "ERROR: CSVの１行目に重複するIDまたはフィールド名が存在します。" },
		{ "ImportData", "タブ区切データ(.txt)のインポート" },
		{ "ImportDataMessage1", "インポート処理が完了しました。" },
		{ "ImportDataMessage2", "件が追加され、" },
		{ "ImportDataMessage3", "件についてはキー値が既存であるために追加されませんでした。" },
		{ "ImportDataMessage4", "ERROR: データ形式が正しくありません。" },
		{ "ImportDataMessage5", "ERROR: １行目に重複するIDまたはフィールド名が存在します。" },
		{ "ImportDialogModelTitle", "モデル情報ファイルからのインポート" },
		{ "ImportDialogTitle", "システム定義ファイルからのインポート" },
		{ "ImportLayout", "インポート" },
		{ "ImportMessage0", "現在のファイル内容が変更されています。インポート処理の前に保存する必要があります。" },
		{ "ImportMessage1", "＊インポートしたいテーブルや機能をチェックして「インポート」のボタンを押してください。定義上のＩＤがインポート先サブシステム以外のサブシステムに存在する場合、その処理区分は「UNMATCH」と示され、存在しない結合テーブルを含むテーブル定義については「NO_JOINNED」と示され、それらをチェックしてもインポートされません。" },
		{ "ImportMessage2", "正常にマージされました。"},
		{ "ImportMessage3", "正常に置換されました。"},
		{ "ImportMessage4", "正常に追加されました。"},
		{ "ImportMessage5", "定義要素に不整合が見つかったため、除外されました。"},
		{ "ImportMessage6", "インポート先サブシステム以外のサブシステムに既存であるため、除外されました。"},
		{ "ImportMessage7", "結合されているテーブルの定義を事前にインポートする必要があります。"},
		{ "ImportMessage8", "一部の結合テーブルのキー指定が正しくありません。"},
		{ "ImportMessage9", "一部の結合フィールドの指定が正しくありません。"},
		{ "ImportMessage10", "一次識別子は変更できません。"},
		{ "ImportMessage11", "一次テーブルのテーブル定義が存在しません。"},
		{ "ImportMessage12", "一次テーブルのキー指定が正しくありません。"},
		{ "ImportMessage13", "明細一覧順の指定が正しくありません。"},
		{ "ImportMessage14", "一部の明細フィールドの指定が正しくありません。"},
		{ "ImportMessage15", "一部の検索条件の指定が正しくありません。"},
		{ "ImportMessage16", "バッチテーブルのテーブル定義が存在しません。"},
		{ "ImportMessage17", "バッチ条件の指定が正しくありません。"},
		{ "ImportMessage18", "一部のフィールドの指定が正しくありません。"},
		{ "ImportMessage19", "見出しテーブルのテーブル定義が存在しません。"},
		{ "ImportMessage20", "見出しテーブルのキー指定が正しくありません。"},
		{ "ImportMessage21", "一部の見出しフィールドの指定が正しくありません。"},
		{ "ImportMessage22", "明細テーブルのテーブル定義が存在しません。"},
		{ "ImportMessage23", "明細テーブルのキー指定が正しくありません。"},
		{ "ImportMessage24", "一部の明細フィールドの指定が正しくありません。"},
		{ "ImportMessage25", "行追加用リストテーブルのテーブル定義が存在しません。"},
		{ "ImportMessage26", "行追加用リストテーブルのキー指定が正しくありません。"},
		{ "ImportMessage27", "行追加用リストの一覧順の指定が正しくありません。"},
		{ "ImportMessage28", "行追加用リストの交換フィールドの指定が正しくありません。"},
		{ "ImportMessage29", "行追加用リスト明細フィールドの一部の指定が正しくありません。"},
		{ "ImportMessage30", "機能タイプが正しくありません。"},
		{ "ImportMessage31", "フレーズ別フォントの指定が正しくありません。"},
		{ "ImportMessage32", "明細フォントの指定が正しくありません。"},
		{ "ImportMessage33", "データベースの指定が正しくありません。"},
		{ "ImportMessage34", "構成テーブルの指定が正しくありません。"},
		{ "ImportMessage35", "構成ノードテキストの指定が正しくありません。"},
		{ "ImportMessage36", "構成ノードアイコン制御フィールドの指定が正しくありません。"},
		{ "ImportModelMessage0", "＊インポートしたいテーブルや機能を含むサブシステムを選んでください。選択されたサブシステムがインポート先に存在しない場合、インポート時に自動的に作成されます。" },
		{ "ImportModelMessage1", "＊一覧上の行を選択して「インポート」のボタンを押せば個々に処理されます。インポート時にＩＤを変更することもできます。" },
		{ "ImportModelMessage2", "このＩＤの要素がいずれかのサブシステムに既存であるため、インポートできません。"},
		{ "ImportModelMessage3", "＊インポート先に存在しない定義です。インポートすることで追加されます。"},
		{ "ImportModelMessage4", "必要に応じてＩＤを変更してください。"},
		{ "ImportModelMessage5", "＊IDがブランクなので、インポートできません。"},
		{ "ImportModelMessage6", "一次テーブルを特定できないため、インポートできません。"},
		{ "ImportModelMessage7", "指定されている一次テーブルが未定義のため、インポートできません。"},
		{ "ImportModelMessage8", "見出しテーブルを特定できないため、インポートできません。"},
		{ "ImportModelMessage9", "指定されている見出しテーブルが未定義のため、インポートできません。"},
		{ "ImportModelMessage10", "有効な明細テーブルを特定できないため、インポートできません。"},
		{ "ImportModelMessage11", "指定されている明細テーブルが未定義のため、インポートできません。"},
		{ "ImportModelMessage12", "機能タイプが規定のものではないため、インポートできません。"},
		{ "ImportModelMessage13", "一部のフィールドのデータ型が規定のものではないため、インポートできません。"},
		{ "ImportModelMessage14", "一部のフィールドのＩＤがブランクのため、インポートできません。"},
		{ "ImportModelMessage15", "正常にインポートされました。"},
		{ "ImportModelMessage16", "見出しテーブルの主キーが明細テーブルの「上位キー」でないため、インポートできません。"},
		{ "ImportModelMessage17", "一部のフィールドのＩＤがテーブル内で重複しているため、インポートできません。"},
		{ "ImportModelMessage18", "＊定義内容が異なります。インポートすれば反映されます（差異によっては無視されます）。"},
		{ "ImportModelMessage19", "＊定義が一致しているのでインポートする必要はありません。"},
		{ "ImportModelMessage20", "＊エラーを含むため、インポートできません。"},
		{ "ImportModelMessage21", "この要素の名前がインポート先での「"},
		{ "ImportModelMessage22", "」と異なる"},
		{ "ImportModelMessage23", "この要素の所属サブシステムがインポート先での「"},
		{ "ImportModelMessage24", "の"},
		{ "ImportModelMessage25", "が追加されている"},
		{ "ImportModelMessage26", "が存在しない"},
		{ "ImportModelMessage27", "が定義されている"},
		{ "ImportModelMessage28", "この要素のタイプがインポート先での「"},
		{ "ImportModelMessage29", "<エラー内容>"},
		{ "ImportModelMessage30", "<インポート元での定義の違い>"},
		{ "ImportSaveMessage", "インポート処理の結果を保存しますか？" },
		{ "ImportSaveTitle", "X-TEA Editor - インポート保存確認" },
		{ "ImportXEAD", "モデル情報ファイル(*.xead)より" },
		{ "ImportXEAF", "システム定義ファイル(*.xeaf)より" },
		{ "Index", "インデックス" },
		{ "InitialListing", "起動時に一覧表示する" },
		{ "InitialMessage", "初期メッセージ" },
		{ "InitialReadCount", "初期検索件数" },
		{ "InitialValue", "条件初期値" },
		{ "InputAssistList", "候補リスト" },
		{ "InsertInitialRecordData1", "ログイン認可フラグ" },
		{ "InsertInitialRecordData2", "システム管理者" },
		{ "InsertInitialRecordData3", "標準" },
		{ "InsertInitialRecordData4", "正社員" },
		{ "InsertInitialRecordData5", "パート" },
		{ "InsertInitialRecordData6", "対象" },
		{ "InsertInitialRecordData7", "対象外" },
		{ "JavaVersionError1", "Javaのバージョンが " },
		{ "JavaVersionError2", " であるためにX-TEA Editorを起動できません。\n規定のバージョンは1.7～1.8です。" },
		{ "JoinField", "結合フィールド" },
		{ "JoinFields", "結合フィールド" },
		{ "JoinRecordExist", "レコード存在条件" },
		{ "JoinRecordOptional", "オプショナル" },
		{ "JoinTable", "結合テーブル" },
		{ "JoinTables", "結合テーブル" },
		{ "JoinTableWithAlias", "結合テーブル、エイリアス＝" },
		{ "JoinToKeys", "結合先KEY項目" },
		{ "JoinWithKeys", "結合元KEY項目" },
		{ "Jump", "ジャンプ" },
		{ "JumpTo1", "「" },
		{ "JumpTo2", "」へジャンプ" },
		{ "JumpToBookmark", "しおりへジャンプ" },
		{ "KeyFieldID", "キーフィールドID" },
		{ "KeyFieldName", "キーフィールド名" },
		{ "KeyFieldOfDTLTable", "明細テーブルの処理キー" },
		{ "KeyFieldOfHDRTable", "見出しテーブルの処理キー" },
		{ "KeyFieldOfPrimaryTable", "一次テーブルの処理キー" },
		{ "KeyFields", "KEYフィールド" },
		{ "Key", "キー" },
		{ "Keys", "ＫＥＹ" },
		{ "KeyType", "KEYタイプ" },
		{ "KeywordList", "Keyword一覧" },
		{ "Launch", "システム起動" },
		{ "LaunchSystemTitle", "現在のファイル内容が変更されています。実行の前に保存する必要があります。" },
		{ "LayoutHidden", "非表示" },
		{ "LayoutHorizontal", "水平配置" },
		{ "LayoutOption", "配置オプション" },
		{ "LayoutVertical", "垂直配置" },
		{ "Lines", "行" },
		{ "List", "一覧" },
		{ "ListBox", "リストボックス" },
		{ "ListItemMark", "･" },
		{ "ListCsv", "CSV出力" },
		{ "ListingOperations", "検索対象操作" },
		{ "ListLog", "操作ログ" },
		{ "ListLogComment", "＊X-TEA Driverが立ち上げたセッションの中で実行された操作のみが検索対象です。また、一意キー（またはその一部）の値指定がWHERE条件に含まれる操作のみが検索対象です。条件を設定して検索ボタンを押してください。" },
		{ "ListLogMessage1", "件の操作ログが見つかりました。行を選択すれば詳細が示されます。" },
		{ "ListLogMessage2", "条件に合う操作ログが見つかりません。" },
		{ "ListLogTitle", "テーブル操作ログ" },
		{ "ListOrder", "一覧順" },
		{ "ListTable", "リストテーブル" },
		{ "LoginScript", "ログインスクリプト" },
		{ "LoginTime", "ログイン日時" },
		{ "MainDB", "メインＤＢ" },
		{ "MainMenuEdit", "編集(E)" },
		{ "MainMenuFile", "ファイル(F)" },
		{ "MainMenuHelp", "ヘルプ(H)" },
		{ "MainMenuScan", "検索(S)" },
		{ "MainMenuTools", "ツール(T)" },
		{ "Margin", "左右マージン" },
		{ "Menu", "メニュー" },
		{ "Menu/Option", "メニュー定義／オプション" },
		{ "MenuCrossCheckers", "Ｘチェッカーのプリロード" },
		{ "MenuFunctions", "機能のプリロード" },
		{ "MenuDefinition", "メニュー定義" },
		{ "MenuDefinitions", "メニュー定義" },
		{ "MenuHelpURL", "操作援助URL" },
		{ "MenuID", "メニューID" },
		{ "MenuIDAndName", "メニューID/名称" },
		{ "MenuList", "メニュー一覧" },
		{ "MenuName", "メニュー名" },
		{ "MenuOption", "メニューオプション" },
		{ "MenuOptionName", "オプション記述" },
		{ "MenuOptions", "メニューオプション" },
		{ "MenuTree", "メニューツリー" },
		{ "Message", "メッセージ" },
		{ "MinusRejectMessage", "この項目でのマイナス符号は無視されます。" },
		{ "ModuleCheck", "モジュールチェック" },
		{ "ModuleCheckMessage1", "フィールド " },
		{ "ModuleCheckMessage2", " の型またはサイズが異なります。\n．．．定義上は" },
		{ "ModuleCheckMessage3", "ですが、モジュール上では" },
		{ "ModuleCheckMessage4", "です。\n" },
		{ "ModuleCheckMessage5", "フィールド " },
		{ "ModuleCheckMessage6", " は定義上は Null可で すが、モジュール上では Null不可 です。\n" },
		{ "ModuleCheckMessage7", "フィールド " },
		{ "ModuleCheckMessage8", " は定義上は Null不可で すが、モジュール上では Null可 です。\n" },
		{ "ModuleCheckMessage9", "フィールド " },
		{ "ModuleCheckMessage10", " がモジュール上に存在しません。\n" },
		{ "ModuleCheckMessage11", "モジュール上の更新排他制御用フィールド " },
		{ "ModuleCheckMessage12", " が INTEGER でなく" },
		{ "ModuleCheckMessage13", " です。\n" },
		{ "ModuleCheckMessage14", "更新排他制御用フィールド " },
		{ "ModuleCheckMessage15", " がモジュール上に存在しません。\n" },
		{ "ModuleCheckMessage16", "モジュール上にフィールド " },
		{ "ModuleCheckMessage17", " が未定義の物理フィールドとして存在します。\n" },
		{ "ModuleCheckMessage18", "モジュール上のユニークキー " },
		{ "ModuleCheckMessage19", " がテーブル定義上に設定されていません。\n" },
		{ "ModuleCheckMessage20", "モジュール上のインデックス " },
		{ "ModuleCheckMessage21", " がテーブル定義上に設定されていません。\n" },
		{ "ModuleCheckMessage22", "一次識別子の定義が異なります。定義上は " },
		{ "ModuleCheckMessage23", " ですが、モジュール上では " },
		{ "ModuleCheckMessage24", " です。\nモジュールが存在する場合に一次識別子の変更はできないため、モジュールをいったん削除する必要があります。\n" },
		{ "ModuleCheckMessage25", "二次識別子 " },
		{ "ModuleCheckMessage26", " の定義がモジュール上に存在しません。\n" },
		{ "ModuleCheckMessage27", "インデックス " },
		{ "ModuleCheckMessage28", " の定義がモジュール上に存在しません。「モジュール修正」を実行してください。\n" },
		{ "ModuleCheckMessage29", "定義上では一次識別子を伴いませんが、モジュール上では " },
		{ "ModuleCheckMessage30", " が一次識別子です。\n" },
		{ "ModuleCheckMessage31", "モジュールが存在しません。" },
		{ "ModuleCheckMessage32", "．．．定義を完成させたうえで「モジュール作成」を実行してください。" },
		{ "ModuleCheckMessage33", "．．．モジュールをいったん削除したうえで、あらたに作成する必要があります。" },
		{ "ModuleCheckMessage34", "．．．「モジュール修正」を実行すれば、モジュール上のフィールドが破棄または属性変更されます。型を変更すればそのフィールドについてデータは初期化され、サイズを短縮する場合にもデータの一部が失われる点に注意してください。\n\nなお、変更内容によっては１回で修正しきれないことがあります。その場合には、何度か実行してください。また、テーブルモジュール上の不要な二次識別子を除くためには、ＳＱＬコンソールを用いてテーブル制約のDROP操作を実行する必要があります。詳しくはHELPで確認してください。" },
		{ "ModuleCheckMessage35", "＊定義とモジュールは同期しています。再作成の必要はありません。" },
		{ "ModuleCheckMessage36", "既存のモジュールが定義にもとづいて\n修正されます。実行しますか？" },
		{ "ModuleCheckMessage37", "モジュールを修正できませんでした。カラムを追加する際に、NULL可でなければエラーになることがあります。\n\n" },
		{ "ModuleCheckMessage38", "モジュールを作成するためには、一次識別子が必要です。" },
		{ "ModuleCheckMessage39", "定義にもとづいてモジュールが新規作成されます。\n作成後に一次識別子を変更するためには、モジュールを\nいったん削除する必要があります。新規作成しますか？" },
		{ "ModuleCheckMessage40", "モジュールを作成できませんでした。\n\n" },
		{ "ModuleCheckMessage41", "既存のモジュールが削除\nされます。実行しますか？" },
		{ "ModuleCheckMessage42", "モジュールを削除できませんでした。" },
		{ "ModuleCheckMessage43", "＊定義にもとづいてモジュールが作成されました。" },
		{ "ModuleCheckMessage44", "＊定義とモジュールが同期されました。必要に応じてデータを修正してください。" },
		{ "ModuleCheckMessage45", "＊定義とモジュールは同期しています。再作成の必要はありませんが、X-TEA Driverにおいて必要とされない外部キー制約がモジュールに組み込まれています。" },
		{ "ModuleCheckMessage46", "一次識別子に含まれるフィールドのタイプか桁数が異なります。" },
		{ "ModuleCheckMessage47", "現在のモジュールにもとづいて不足分のフィールド定義を補完します。\n未対応のデータ型のフィールドについてはCHAR型で追加されます。" },
		//{ "ModuleCheckMessage48", " の型またはサイズが異なります。\n．．．定義上は全角文字ですが、モジュール上では半角文字です。" },
		{ "ModuleCheckMessage48", " の型またはサイズが異なります。\n．．．定義上は漢字の" },
		{ "ModuleCreate", "モジュール作成" },
		{ "ModuleDelete", "モジュール削除" },
		{ "ModuleModify", "モジュール修正" },
		{ "ModulePut", "定義の補完" },
		{ "Name", "名称" },
		{ "NameDialogTitle", "X-TEA Editor - フォルダとファイル名（漢字不可）を指定してください。" },
		{ "NewScript", "新規スクリプト" },
		{ "NewTab", "新規タブ" },
		{ "Next", "次へ" },
		{ "No", "いいえ" },
		{ "NoCaption", "キャプションなし" },
		{ "NoFieldsLeftToBeAdded", "追加可能なフィールド定義が残っていません。" },
		{ "None", "なし" },
		{ "NonEditable", "入力不可" },
		{ "NoUpdate", "更新不可" },
		{ "NumberFormatError", "小数点は入力できません。" },
		{ "Nullable", "NULL可" },
		{ "NullCheckMessage", "何らかの値を入力してください。" },
		{ "Open", "開く" },
		{ "OpenExistintContent", "既存のコンテンツファイルを開く" },
		{ "OpenMessage", "現在のファイル内容が変更されています。保存してから開きますか？" },
		{ "OpenNotSaving", "保存せずに開く" },
		{ "OpenSaving", "保存してから開く" },
		{ "OpenXEAFFile", "既存のxeafファイルを開く" },
		{ "OptionalList", "省略可リスト" },
		{ "OptionName", "オプション名" },
		{ "Order", "一覧順" },
		{ "OrderByFields", "明細一覧順" },
		{ "OrderByOfDetailList", "明細データの一覧順序" },
		{ "Output", "出力" },
		{ "OutputFolder", "出力フォルダ" },
		{ "OverrideID", "ID変更確認表示" },
		{ "PageDirection", "用紙方向" },
		{ "PageMargins", "左右上下マージン" },
		{ "PageNo", "ページ番号出力" },
		{ "PageSize", "用紙サイズ" },
		{ "PanelSize", "パネルサイズ" },
		{ "Parameters", "交換値" },
		{ "ParmAdditional", "明細処理機能の追加交換値" },
		{ "Password", "パスワード" },
		{ "Paste", "貼り付け" },
		{ "PasteChild", "下位要素を貼り付け" },
		{ "PasteFromClipboard", "貼り付け" },
		{ "PasteToClipboard", "コピー" },
		{ "PhraseBlock", "ブロック" },
		{ "PhraseFormula", "フレーズ式" },
		{ "PhraseSpacingAfter", "後スペース" },
		{ "PhysicalField", "物理フィールド" },
		{ "PKey", "一次識別子" },
		{ "Pos_short", "位置" },
		{ "Position", "位置" },
		{ "Previous", "戻る" },
		{ "PrimaryTable", "一次テーブル" },
		{ "PrintFont", "印刷用フォント名" },
		{ "ProcessRowIfOnlyOne", "１行だけなら明細処理実行" },
		{ "ProcessType", "処理区分" },
		{ "Prompt", "プロンプタ" },
		{ "PrompterFunction", "関数検索" },
		{ "PrompterFunctionExchange", "プロンプタ機能との交換フィールド" },
		{ "PrompterList", "リスト選択" },
		{ "ReadCheckMessage", "件が読み取られました。次の読取件数を指定してください。" },
		{ "ReadCountMessage", "件のデータが見つかりました。" },
		{ "ReadEmptyMessage", "テーブルは空です。" },
		{ "ReadNoneMessage", "条件に合うデータが見つかりません。" },
		{ "ReadOnlyWarning1", "指定されたファイルは読み取り専用です。X-TEA Editorで編集" },
		{ "ReadOnlyWarning2", "しても、その内容を反映できない点にご注意ください。" },
		{ "Redo", "ノードに対する変更をやり直す" },
		{ "Refer", "結合テーブル" },
		{ "Refresh", "再表示" },
		{ "Remarks", "説明" },
		{ "RemoveRow", "行削除" },
		{ "ReplaceAllSelected", "選択行について一括置換" },
		{ "ReplaceFile", "上書き" },
		{ "ReplaceSaveMessage", "置換処理の結果を保存しますか？" },
		{ "ReplaceSaveTitle", "X-TEA Editor - 置換保存確認" },
		{ "RequiredList", "強制リスト" },
		{ "Result", "結果" },
		{ "RetrieveLog", "操作ログの検索" },
		{ "Return", "終了" },
		{ "ReturnFields", "返しフィールド" },
		{ "RowAction", "明細選択時" },
		{ "RowActionCall", "機能を起動" },
		{ "RowActionReturn", "起動元に返す" },
		{ "RowNoWidth", "行№幅比率" },
		{ "Save", "保存" },
		{ "SaveAs", "別名で保存" },
		{ "SaveAsThis", "この名前で保存" },
		{ "SaveChanges", "保存する" },
		{ "SaveChangesTitle", "X-TEA Editor - 変更の保存" },
		{ "Scan", "走査" },
		{ "ScanDialogComment1", "Editorで編集可能な定義要素のみ検索され、IDやテーブルエイリアスといった編集不可項目は除外される点に注意してください。" },
		{ "ScanDialogComment2", "個の定義要素の、" },
		{ "ScanDialogComment3", "箇所で指定文字列が見つかりました。行を選択すれば属性値が示されます。" },
		{ "ScanDialogComment4", "指定文字列を含む定義要素は見つかりませんでした。" },
		{ "ScanDialogComment5", "個の定義要素の、" },
		{ "ScanDialogComment6", "箇所で指定文字列が置換されました。" },
		{ "ScanDialogTitle", "文字列の走査・置換" },
		{ "ScanField", "フィールド定義の走査" },
		{ "ScanFieldFound", "件のフィールド定義が見つかりました。" },
		{ "ScanFieldHintMessage", "＊文字列をセミコロン( ; )で区切って指定すれば、OR条件の一致条件とみなされます。文字列の前や後にアスタリスク(*)を置けば総称指定になります。" },
		{ "ScanFieldNotFound", "条件に見合うフィールド定義が１件も見つかりませんでした。" },
		{ "ScanMessage", "現在のファイル内容が変更されています。検索・置換の前に保存する必要があります。" },
		{ "ScanRange", "走査範囲" },
		{ "ScanReplace", "文字列の走査・置換" },
		{ "ScanStart", "走査開始" },
		{ "ScanString", "走査文字列" },
		{ "ScanStringInScript", "走査文字列" },
		{ "ScanStringInScriptMessage", "指定文字列が見つかりません。" },
		{ "ScanStringReplacedTo", "置換文字列" },
		{ "Script", "スクリプト" },
		{ "ScriptChangesMessage", "スクリプトの編集結果を保存しますか？" },
		{ "ScriptEditorFunctionKeys1", "F1=HELP　F7=構文検査　F3=文字列検索（カーソル位置から）" },
		{ "ScriptEditorFunctionKeys2", "Ctrl+I=インデント　Ctrl+N=NAME/ID　Ctrl+/=コメント" },
		{ "ScriptError", "スクリプトに構文エラーがあります。エラー内容と行番を確認してください" },
		{ "ScriptErrorNotFound", "構文エラーは見つかりませんでした。" },
		{ "ScriptFontSize", "スクリプトの文字サイズ" },
		{ "ScriptFunctions", "スクリプト関数" },
		{ "ScriptHold", "一時保留" },
		{ "ScriptNotesTitle1", "■フィールド値変数一覧" },
		{ "ScriptNotesTitle2", "\n\n■結合フィールド値変数一覧" },
		{ "ScriptNotesTitle3", "\n\n■変数名凡例\n[TableID]_[FieldID].value : フィールド値\n[TableID]_[FieldID].oldValue : 更新前のフィールド値。読取専用\n[TableID]_[FieldID].valueChanged : 値が変更されたかどうか(true,false)。読取専用\n[TableID]_[FieldID].color : 表示色(black,green,blue,red,orange)\n[TableID]_[FieldID].enabled : 有効設定(true,false)\n[TableID]_[FieldID].editable : 編集設定(true,false)\n[TableID]_[FieldID].valueList : 選択可能値リスト（配列）\n[TableID]_[FieldID].error : エラーメッセージ\n（セッションオブジェクトや機能オブジェクトも利用可能です。詳細についてはヘルプで確認してください）" },
		{ "ScriptNotesVFMark", "(仮) " },
		{ "Scripts", "スクリプト" },
		{ "Sel", "選" },
		{ "SelectAll", "全選択" },
		{ "SelectContent", "X-TEA Editor - 編集ファイルの選択" },
		{ "SelectFile", "ファイルを選んで開く" },
		{ "SelectFromList", "（選択してください）" },
		{ "SelectList", "選択リスト" },
		{ "ServiceName", "サービス名" },
		{ "SessionNo", "セッション№" },
		{ "Size", "サイズ" },
		{ "SizeAuto", "自動設定" },
		{ "SizeFull", "全画面" },
		{ "SizeSpecified", "指定値（横縦）" },
		{ "SKey", "二次識別子" },
		{ "SkipModuleCheck", "Editor起動時にモジュールチェックをスキップ" },
		{ "SkipPreload", "Driver起動時にプリロードをスキップ" },
//		{ "SmtpHost", "SMTPホスト名" },
//		{ "SmtpPort", "ポート" },
//		{ "SmtpUser", "ユーザID" },
//		{ "SmtpPassword", "パスワード" },
		{ "SpecifyFunctionID", "機能ＩＤを指定してください。" },
		{ "SpecifyName", "ファイル名の再指定" },
		{ "SpecifyNewID", "新たなＩＤを指定してください。" },
		{ "SplashMessage0", "X-TEA Editorを起動中" },
		{ "SplashMessage1", "システム定義を分析中" },
		{ "SplashMessage2", "データベースへ接続中" },
		{ "SplashMessage3", "テーブル定義を分析中" },
		{ "SplashMessage4", "機能定義を分析中" },
		{ "SqlCommitF5", "実行  F5" },
		{ "SqlConsole", "SQLコンソール" },
		{ "SqlConsoleComment", "＊SQLステートメントの他、システム組込プロシージャも実行できます。ただし、ここでCREATE TABLEを実行しても、テーブル定義は設計情報として追加されません。テーブル定義を作成したい場合には「ツール｜テーブル定義作成」を用いてください。「モジュール一覧」を押せば、選択されているDB上に存在するテーブルモジュールが一覧されます。\n" },
		{ "SqlConsoleMessage1", "・・・正常に実行されました。\n(" },
		{ "SqlConsoleMessage2", "操作に失敗しました。" },
		{ "SqlListModules", "モジュール一覧" },
		{ "Start", "スタート" },
		{ "Status", "状況" },
		{ "StrNodeIconField", "構成ノードアイコンフィールド" },
		{ "StrNodeText", "構成ノードテキストフィールド" },
		{ "StrRootText", "構成ルートテキストフィールド" },
		{ "StrUpperKeyField", "構成上位キーフィールド" },
		{ "StrChildKeyField", "構成再帰キーフィールド" },
		{ "StructureChildKeys", "構成再帰キー" },
		{ "StructureNodeDefaultIcon", "省略時アイコン" },
		{ "StructureNodeIcons", "ノードアイコン" },
		{ "StructureNodeIconsComment", "制御フィールドには見出しテーブルの物理フィールドを１個指定してください。フィールド値の順序にしたがってアイコンファイル名を';'で区切って並べてください。" },
		{ "StructureNodeIconsFieldID", "制御フィールド" },
		{ "StructureNodeIconsFieldValues", "制御値リスト" },
		{ "StructureNodeIconsList", "アイコンリスト" },
		{ "StructureNodeIconsTitle", "ノードアイコンの設定" },
		{ "StructureNodeText", "ノードテキスト" },
		{ "StructureNodeTextRemarks", "見出しテーブルまたは構成テーブル上の物理データソース名を';'でつなげて\n指定してください。クォーテーション(')で固定文字値を含めることもできます。" },
		{ "StructureOrderBy", "構成一覧順" },
		{ "StructureRootText", "ルートテキスト" },
		{ "StructureRootTextRemarks", "見出しテーブル上の物理フィールドＩＤを';'でつなげて指定して\nください。クォーテーション(')で固定文字値を含めることもできます。" },
		{ "StructureTable", "構成テーブル" },
		{ "StructureTableComment", "構成上位キーは「親」の主キーとタイプが一致していなければなりません。構成再帰キーとは、構成テーブル上のフィールドのうち「子」の主キーに対応する部分のことです。" },
		{ "StructureTableTitle", "構成テーブルの設定" },
		{ "StructureUpperKeys", "構成上位キー" },
		{ "StructureView", "構成ツリー" },
		{ "StructureViewTitle", "ツリービューキャプション" },
		{ "StructureViewWidth", "ツリービュー幅" },
		{ "SubDB", "サブＤＢ" },
		{ "Subsystem", "サブシステム定義" },
		{ "SubsystemDescriptions", "サブシステム記述" },
		{ "SubsystemFunctions", "機" },
		{ "SubsystemID", "サブシステムID" },
		{ "SubsystemIDAndName", "サブシステムID/名称" },
		{ "SubsystemImportingFrom", "インポート元サブシステム" },
		{ "SubsystemImportingInto", "先サブシステム" },
		{ "SubsystemName", "サブシステム名" },
		{ "SubsystemRemarks", "サブシステムの説明" },
		{ "SubsystemTables", "表" },
		{ "System", "システム定義" },
		{ "SystemCalendar", "休日テーブル" },
		{ "SystemDatabaseConfig", "データベース設定" },
		{ "SystemOtherConfig", "その他の設定" },
		{ "SystemDefinition", "システム定義" },
		{ "SystemDescriptions", "システム記述" },
		{ "SystemExchangeRateAnnual", "年次為替レート" },
		{ "SystemExchangeRateMonthly", "月次為替レート" },
		{ "SystemInfo", "基本情報" },
		{ "SystemMaintenanceLog", "保守履歴" },
		{ "SystemMaintenanceLogVersion", "バージョン等" },
		{ "SystemMaintenanceLogDateTime", "改版日時" },
		{ "SystemMaintenanceLogSortKey", "改版日時(一覧順)" },
		{ "SystemMaintenanceLogRemarks", "変更内容" },
		{ "SystemName", "システム名" },
		{ "SystemNameImporting", "インポート元システム" },
		{ "SystemNumbering", "採番テーブル" },
		{ "SystemRemarks", "システムの説明" },
		{ "SystemSession", "セッション" },
		{ "SystemSessionDetail", "セッション明細" },
		{ "SystemTax", "消費税" },
		{ "SystemUser", "ユーザ情報" },
		{ "SystemUserFilterValue", "ユーザフィルター値" },
		{ "SystemUserVariants", "ユーザ定義区分" },
		{ "SystemVariants", "システム変数" },
		{ "SystemVersion", "バージョン" },
		{ "TabbedFields", "タブ別フィールド" },
		{ "Table", "テーブル" },
		{ "TableDefinition", "テーブル定義" },
		{ "TableDefinitions", "テーブル定義" },
		{ "Table/Field", "テーブル定義／フィールド" },
		{ "Table/Script", "テーブル定義／スクリプト" },
		{ "TableID", "テーブルID" },
		{ "TableIDAndName", "テーブルID/名称" },
		{ "TableKey", "処理KEY" },
		{ "TableList", "テーブル一覧" },
		{ "TableModuleCheck", "モジュールチェック" },
		{ "TableModuleID", "モジュールID" },
		{ "TableName", "テーブル名" },
		{ "TableOperation", "テーブル操作" },
//		{ "TableReferCheck", "クロスチェック対象" },
		{ "TableUsageInScript1", "スクリプト「" },
		{ "TableUsageInScript2", "」での操作(" },
		{ "TableUsageInScript3", ")" },
		{ "TableUsageInScript4", "スクリプトでの操作(" },
		{ "Text", "テキスト" },
		{ "TimerDefault", "時刻初期値" },
		{ "TimerMessage", "メッセージ" },
		{ "TipsFunction", "機能の所属サブシステムは変更可能です。ツリービューの別の\nサブシステム下の機能ノードをここにドラッグ＆ドロップすれば、\nこのサブシステムに所属する定義として変更されます。" },
		{ "TipsMenu", "ツリービューの機能ノードをここにドラッグ＆ドロップ\nすることでも、メニューオプションとして組み込めます。" },
		{ "TipsTable", "テーブルの所属サブシステムは変更可能です。ツリービューの\n別のサブシステム下のテーブルノードをここにドラッグ＆ドロップ\nすれば、このサブシステムに所属する定義として変更されます。" },
		{ "TipsTitle", "編集のヒント" },
		{ "TipsToEdit", "編集のヒント" },
		{ "Tools", "ツール" },
		{ "Type", "タイプ" },
		{ "TypeOptions", "タイプオプション" },
		{ "Undo", "ノードに対する変更を取り消す" },
		{ "UndoAdd", "を追加" },
		{ "UndoModify", "を変更" },
		{ "UndoRemove", "を削除" },
		{ "Update", "更新" },
		{ "UpdateCounter", "更新排他制御" },
		{ "UpdateList", "更新リスト" },
		{ "UpdateMessage", "更新前メッセージ" },
		{ "UsageBatchFieldPrompter", "バッチフィールドプロンプタ" },
		{ "UsageColumnPrompter", "明細フィールドプロンプタ" },
		{ "UsageDTLFunction", "明細呼出機能" },
		{ "UsageFieldPrompter", "フィールドプロンプタ" },
		{ "UsageHDRFunction", "見出し呼出機能" },
		{ "UsageLaunchedAfterInsert", "追加後呼出機能" },
		{ "UsageLaunchedByBatchRecord", "バッチレコード処理機能" },
		{ "UsageLaunchedByFunctionKey", "機能キー呼出機能" },
		{ "UsageLaunchedByRow", "明細呼出機能" },
		{ "UsageLaunchedInScript", "スクリプト呼出機能" },
		{ "User", "ユーザ" },
		{ "UserID", "ユーザID" },
		{ "ValueSpecified", "指定値" },
		{ "VariantNameOnScript", "スクリプト上の変数名" },
		{ "Virtual", "仮想" },
		{ "WarningMessage1", "警告：この結合フィールドのデータソース名が、バッチテーブル上で\n重複しています。詳細はHELPで確認してください。" },
		{ "WarningMessage2", "警告：この結合フィールドのデータソース名が、一次テーブル上で\n重複しています。詳細はHELPで確認してください。" },
		{ "WarningMessage3", "警告：この結合フィールドのデータソース名が、明細テーブル上で\n重複しています。詳細はHELPで確認してください。" },
		{ "WarningMessage4", "警告：この結合フィールドのデータソース名が、見出しテーブル上で\n重複しています。詳細はHELPで確認してください。" },
		{ "WelcomePageURL", "メニュー用URL" },
		{ "WhereUsed", "使途要素" },
		{ "WhereUsedForm", "利用形式" },
		{ "WhereUsedTable", "使途テーブル名" },
		{ "Width", "幅" },
		{ "WidthRate", "幅比率" },
		{ "WithTotal", "合計出力" },
		{ "XLSComment", "＊この一覧は次の条件で絞込み、または並び順の指定がなされています：" },
		{ "XLSErrorMessage", "エクセルデータの出力エラーが発生しました。" },
//		{ "XLSFontDTL", "ＭＳ Ｐ明朝" },
//		{ "XLSFontHDR", "ＭＳ Ｐゴシック" },
		{ "Yes", "はい" }
	};

	public Object[][] getContents() {
		return contents;
	}
}
